import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  adminShell: {
    backgroundColor: '#F4FAF6',
    flex: 1,
  },
  adminScroll: {
    flex: 1,
  },
  adminLayout: {
    gap: 10,
  },
  adminPathRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 7,
  },
  adminPathMuted: {
    color: '#557669',
    fontSize: 13,
    fontWeight: '800',
  },
  adminPathDivider: {
    color: '#557669',
    fontSize: 13,
    fontWeight: '800',
  },
  adminPathActive: {
    color: '#008D49',
    fontSize: 13,
    fontWeight: '900',
  },
  adminWorkbench: {
    gap: 12,
    padding: 12,
  },
  adminWorkbenchCopy: {
    flex: 1,
    gap: 4,
    minWidth: 0,
  },
  adminWorkbenchGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  adminWorkbenchHeader: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'space-between',
  },
  adminWorkbenchIcon: {
    alignItems: 'center',
    backgroundColor: '#E8F3EF',
    borderRadius: 8,
    height: 34,
    justifyContent: 'center',
    width: 34,
  },
  adminWorkbenchIconActive: {
    backgroundColor: '#008D49',
  },
  adminWorkbenchText: {
    color: '#557669',
    fontSize: 13,
    lineHeight: 18,
  },
  adminWorkbenchTile: {
    backgroundColor: '#FFFFFF',
    borderColor: 'rgba(18, 56, 44, 0.1)',
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    gap: 7,
    minHeight: 112,
    minWidth: 142,
    padding: 10,
  },
  adminWorkbenchTileActive: {
    backgroundColor: '#F1F8F3',
    borderColor: '#008D49',
  },
  adminWorkbenchTileText: {
    color: '#557669',
    fontSize: 12,
    fontWeight: '800',
  },
  adminWorkbenchTileTitle: {
    color: '#12382C',
    fontSize: 15,
    fontWeight: '900',
  },
  adminWorkbenchTileTop: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'space-between',
  },
  adminWorkbenchTitle: {
    color: '#12382C',
    fontSize: 20,
    fontWeight: '900',
  },
  adminBottomTabs: {
    alignItems: 'stretch',
    backgroundColor: '#FFFFFF',
    borderColor: 'rgba(0, 141, 73, 0.18)',
    borderTopWidth: 1,
    flexDirection: 'row',
    gap: 6,
    justifyContent: 'space-between',
    paddingHorizontal: 10,
    paddingTop: 8,
    paddingBottom: 10,
  },
  adminBottomTab: {
    alignItems: 'center',
    borderRadius: 8,
    flex: 1,
    gap: 4,
    justifyContent: 'center',
    minHeight: 58,
    minWidth: 0,
    paddingHorizontal: 4,
    position: 'relative',
  },
  adminBottomTabActive: {
    backgroundColor: '#E8F3EF',
  },
  adminBottomIndicator: {
    backgroundColor: 'transparent',
    borderRadius: 999,
    height: 3,
    position: 'absolute',
    top: 5,
    width: 22,
  },
  adminBottomIndicatorActive: {
    backgroundColor: '#008D49',
  },
  adminBottomIcon: {
    alignItems: 'center',
    borderRadius: 8,
    height: 30,
    justifyContent: 'center',
    width: 30,
  },
  adminBottomIconActive: {
    backgroundColor: '#008D49',
  },
  adminBottomText: {
    color: '#557669',
    fontSize: 11,
    fontWeight: '900',
    textAlign: 'center',
  },
  adminBottomTextActive: {
    color: '#008D49',
  },
  complianceGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginTop: 4,
  },
  complianceLabel: {
    color: '#557669',
    fontSize: 11,
    fontWeight: '800',
  },
  complianceLabelReady: {
    color: '#008D49',
  },
  compliancePill: {
    backgroundColor: '#FFFFFF',
    borderColor: '#008D49',
    borderRadius: 8,
    borderWidth: 1,
    gap: 2,
    minWidth: 104,
    paddingHorizontal: 8,
    paddingVertical: 6,
  },
  compliancePillReady: {
    backgroundColor: '#E8F3EF',
    borderColor: '#008D49',
  },
  complianceValue: {
    color: '#12382C',
    fontSize: 11,
    fontWeight: '900',
  },
  complianceValueReady: {
    color: '#008D49',
  },
  dangerButton: {
    backgroundColor: '#E8F3EF',
    borderColor: '#C17A70',
  },
  dangerButtonText: {
    color: '#C17A70',
    fontSize: 12,
    fontWeight: '900',
  },
  auditBox: {
    borderColor: '#E8F3EF',
    borderTopWidth: 1,
    gap: 3,
    marginTop: 6,
    paddingTop: 8,
  },
  documentMetaText: {
    color: '#81786B',
    fontSize: 11,
    lineHeight: 16,
  },
  documentAccessButton: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: '#E8F3EF',
    borderColor: '#008D49',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 6,
    minHeight: 32,
    paddingHorizontal: 9,
  },
  documentAccessButtonText: {
    color: '#008D49',
    fontSize: 11,
    fontWeight: '900',
  },
  documentRejectText: {
    color: '#C17A70',
    fontSize: 12,
    fontWeight: '800',
    lineHeight: 17,
  },
  documentUploadBox: {
    backgroundColor: '#FFFFFF',
    borderColor: '#008D49',
    borderRadius: 8,
    borderWidth: 1,
    gap: 3,
    marginTop: 4,
    padding: 10,
  },
  documentUploadItem: {
    gap: 2,
  },
  documentUploadText: {
    color: '#557669',
    fontSize: 12,
    lineHeight: 17,
  },
  documentUploadTitle: {
    color: '#12382C',
    fontSize: 13,
    fontWeight: '900',
  },
  backButton: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#008D49',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    minHeight: 42,
    paddingHorizontal: 12,
  },
  backButtonText: {
    color: '#008D49',
    fontSize: 14,
    fontWeight: '900',
  },
  adminTab: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: 'rgba(0, 141, 73, 0.22)',
    borderRadius: 8,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 40,
    paddingHorizontal: 12,
  },
  adminTabActive: {
    backgroundColor: '#008D49',
    borderColor: '#008D49',
  },
  adminTabs: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  adminTabText: {
    color: '#12382C',
    fontSize: 13,
    fontWeight: '900',
  },
  adminTabTextActive: {
    color: '#FFFFFF',
  },
  errorText: {
    color: '#C17A70',
    fontSize: 13,
    fontWeight: '800',
  },
  field: {
    gap: 8,
  },
  dispatcherEntry: {
    alignItems: 'center',
    backgroundColor: '#008D49',
    borderRadius: 16,
    flexDirection: 'row',
    gap: 13,
    padding: 16,
  },
  dispatcherEntryPressed: {
    opacity: 0.82,
  },
  dispatcherEntryIcon: {
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    borderRadius: 13,
    height: 46,
    justifyContent: 'center',
    width: 46,
  },
  dispatcherEntryCopy: {
    flex: 1,
    gap: 3,
  },
  dispatcherEntryTitle: {
    color: '#FFFFFF',
    fontSize: 17,
    fontWeight: '700',
  },
  dispatcherEntryText: {
    color: 'rgba(255, 255, 255, 0.88)',
    fontSize: 13,
    lineHeight: 18,
  },
  headerCard: {
    backgroundColor: '#FFFFFF',
    borderColor: '#008D49',
    borderRadius: 8,
    borderWidth: 1,
    gap: 8,
    padding: 12,
  },
  helperText: {
    color: '#557669',
    fontSize: 12,
    lineHeight: 18,
  },
  hiddenSection: {
    display: 'none',
  },
  iconButton: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#008D49',
    borderRadius: 8,
    borderWidth: 1,
    height: 42,
    justifyContent: 'center',
    width: 42,
  },
  iconWrap: {
    alignItems: 'center',
    backgroundColor: '#E8F3EF',
    borderRadius: 8,
    height: 46,
    justifyContent: 'center',
    width: 46,
  },
  input: {
    backgroundColor: '#FFFFFF',
    borderColor: '#557669',
    borderRadius: 8,
    borderWidth: 1,
    color: '#12382C',
    fontSize: 16,
    minHeight: 48,
    paddingHorizontal: 12,
  },
  disabledButton: {
    opacity: 0.45,
  },
  inlineForm: {
    alignItems: 'stretch',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  inlineInput: {
    flex: 1,
    minWidth: 220,
  },
  label: {
    color: '#12382C',
    fontSize: 14,
    fontWeight: '900',
  },
  loginCard: {
    backgroundColor: '#FFFFFF',
    borderColor: '#008D49',
    borderRadius: 8,
    borderWidth: 1,
    gap: 12,
    padding: 12,
  },
  orderRow: {
    backgroundColor: '#E8F3EF',
    borderColor: '#008D49',
    borderRadius: 8,
    borderWidth: 1,
    gap: 4,
    padding: 10,
  },
  orderText: {
    color: '#557669',
    fontSize: 13,
    lineHeight: 18,
  },
  orderTitle: {
    color: '#12382C',
    fontSize: 14,
    fontWeight: '900',
  },
  mutedButton: {
    opacity: 0.48,
  },
  page: {
    backgroundColor: '#F4FAF6',
    gap: 12,
    minHeight: '100%',
    padding: 14,
    paddingBottom: 18,
  },
  planRow: {
    backgroundColor: '#E8F3EF',
    borderColor: '#008D49',
    borderRadius: 8,
    borderWidth: 1,
    gap: 4,
    padding: 10,
  },
  planTitle: {
    color: '#12382C',
    fontSize: 14,
    fontWeight: '900',
  },
  planValue: {
    color: '#008D49',
    fontSize: 13,
    fontWeight: '900',
  },
  pressed: {
    opacity: 0.92,
    transform: [{ scale: 0.95 }],
  },
  reasonInput: {
    backgroundColor: '#FFFFFF',
    borderColor: '#557669',
    borderRadius: 8,
    borderWidth: 1,
    color: '#12382C',
    fontSize: 13,
    minHeight: 42,
    paddingHorizontal: 10,
  },
  reviewBox: {
    backgroundColor: '#E8F3EF',
    borderColor: '#008D49',
    borderRadius: 8,
    borderWidth: 1,
    gap: 6,
    marginTop: 6,
    padding: 10,
  },
  primaryButton: {
    alignItems: 'center',
    backgroundColor: '#008D49',
    borderRadius: 8,
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'center',
    minHeight: 50,
    paddingHorizontal: 16,
  },
  primaryButtonText: {
    color: '#F4FAF6',
    fontSize: 15,
    fontWeight: '900',
  },
  rowActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  safeArea: {
    backgroundColor: '#F4FAF6',
    flex: 1,
  },
  sectionCard: {
    backgroundColor: '#FFFFFF',
    borderColor: '#008D49',
    borderRadius: 8,
    borderWidth: 1,
    gap: 8,
    padding: 12,
  },
  sectionHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  sectionText: {
    color: '#12382C',
    fontSize: 13,
    lineHeight: 18,
  },
  sectionTextMuted: {
    color: '#557669',
    fontSize: 12,
    lineHeight: 17,
  },
  sectionTitle: {
    color: '#12382C',
    fontSize: 17,
    fontWeight: '900',
  },
  secondaryButton: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#008D49',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'center',
    minHeight: 42,
    paddingHorizontal: 12,
  },
  secondaryButtonText: {
    color: '#008D49',
    fontSize: 13,
    fontWeight: '900',
  },
  smallButton: {
    alignItems: 'center',
    backgroundColor: '#E8F3EF',
    borderColor: '#008D49',
    borderRadius: 8,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 36,
    paddingHorizontal: 10,
  },
  smallButtonText: {
    color: '#008D49',
    fontSize: 12,
    fontWeight: '900',
  },
  statCard: {
    backgroundColor: '#FFFFFF',
    borderColor: '#008D49',
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    gap: 5,
    minWidth: 132,
    padding: 10,
  },
  statHelper: {
    color: '#557669',
    fontSize: 12,
    lineHeight: 17,
  },
  statLabel: {
    color: '#557669',
    fontSize: 12,
    fontWeight: '800',
  },
  statValue: {
    color: '#12382C',
    fontSize: 22,
    fontWeight: '900',
  },
  statsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  statsGridCompact: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  subtitle: {
    color: '#557669',
    fontSize: 14,
    lineHeight: 20,
  },
  title: {
    color: '#12382C',
    fontSize: 24,
    fontWeight: '900',
    lineHeight: 30,
  },
  topBar: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  drawerRoot: {
    flex: 1,
    flexDirection: 'row',
  },
  drawerScrim: {
    backgroundColor: 'rgba(18, 56, 44, 0.34)',
    flex: 1,
  },
  drawerPanel: {
    backgroundColor: '#F4FAF6',
    borderRightColor: 'rgba(0, 141, 73, 0.22)',
    borderRightWidth: 1,
    gap: 12,
    maxWidth: 360,
    padding: 14,
    width: '86%',
  },
  drawerHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'space-between',
  },
  drawerTitleCopy: {
    flex: 1,
    minWidth: 0,
  },
  drawerTitle: {
    color: '#12382C',
    fontSize: 19,
    fontWeight: '900',
  },
  drawerSubtitle: {
    color: '#557669',
    fontSize: 13,
    marginTop: 2,
  },
  drawerClose: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#008D49',
    borderRadius: 8,
    borderWidth: 1,
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  drawerList: {
    gap: 8,
    paddingBottom: 18,
  },
  drawerItem: {
    alignItems: 'flex-start',
    backgroundColor: '#FFFFFF',
    borderColor: 'rgba(0, 141, 73, 0.18)',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    padding: 10,
  },
  drawerItemActive: {
    backgroundColor: '#E8F3EF',
    borderColor: '#008D49',
  },
  drawerIconWrap: {
    alignItems: 'center',
    backgroundColor: '#E8F3EF',
    borderRadius: 8,
    height: 34,
    justifyContent: 'center',
    width: 34,
  },
  drawerIconWrapActive: {
    backgroundColor: '#008D49',
  },
  drawerItemCopy: {
    flex: 1,
    gap: 3,
    minWidth: 0,
  },
  drawerItemTitle: {
    color: '#12382C',
    fontSize: 14,
    fontWeight: '900',
  },
  drawerItemTitleActive: {
    color: '#008D49',
  },
  drawerItemSubtitle: {
    color: '#557669',
    fontSize: 12,
    lineHeight: 17,
  },
});
