import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  actions: {
    gap: 10,
  },
  acceptOrderButton: {
    alignItems: 'center',
    backgroundColor: '#008D49',
    borderRadius: 8,
    elevation: 2,
    flex: 1,
    justifyContent: 'center',
    minHeight: 46,
    paddingHorizontal: 14,
    shadowColor: 'rgba(0, 111, 58, 0.22)',
    shadowOffset: { height: 5, width: 0 },
    shadowOpacity: 0.14,
    shadowRadius: 8,
  },
  acceptOrderButtonText: {
    color: '#F4FAF6',
    fontSize: 15,
    fontWeight: '700',
    textAlign: 'center',
  },
  compactAcceptOrderButton: {
    flex: 1,
    minHeight: 46,
    paddingHorizontal: 12,
  },
  clientBottom: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
  },
  compactOrderActions: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    marginTop: 2,
  },
  compactOrderBadge: {
    backgroundColor: '#F1F8F3',
    borderRadius: 6,
    color: '#008D49',
    fontSize: 11,
    fontWeight: '700',
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  compactOrderBadges: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  compactOrderCard: {
    backgroundColor: '#FFFFFF',
    borderColor: 'rgba(0, 141, 73, 0.16)',
    borderRadius: 8,
    borderWidth: 1,
    elevation: 1,
    gap: 8,
    padding: 12,
    shadowColor: 'rgba(18, 56, 44, 0.16)',
    shadowOffset: { height: 5, width: 0 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
  },
  compactOrderCardActive: {
    borderColor: '#008D49',
    backgroundColor: '#F9FFFB',
  },
  compactOrderMeta: {
    color: '#557669',
    fontSize: 13,
    fontWeight: '600',
    marginLeft: 22,
  },
  compactOrderCopy: {
    flex: 1,
    gap: 5,
    minWidth: 0,
  },
  compactOrderPrice: {
    color: '#006F3A',
    fontSize: 18,
    fontWeight: '900',
    minWidth: 56,
    textAlign: 'right',
  },
  compactOrderRoute: {
    color: '#12382C',
    fontSize: 15,
    fontWeight: '900',
    lineHeight: 19,
    minWidth: 0,
  },
  compactOrderRouteTo: {
    color: '#12382C',
    fontSize: 14,
    fontWeight: '700',
    lineHeight: 18,
    minWidth: 0,
  },
  compactOrderPayment: {
    color: '#557669',
    fontSize: 12,
    fontWeight: '600',
  },
  compactOrderService: {
    backgroundColor: '#EAF6EF',
    borderColor: 'rgba(0, 141, 73, 0.18)',
    borderRadius: 6,
    borderWidth: 1,
    color: '#008D49',
    fontSize: 11,
    fontWeight: '900',
    maxWidth: 78,
    overflow: 'hidden',
    paddingHorizontal: 7,
    paddingVertical: 5,
    textAlign: 'center',
  },
  compactOrderRouteDot: {
    backgroundColor: '#008D49',
    borderRadius: 999,
    height: 8,
    width: 8,
  },
  compactOrderRouteDotEnd: {
    borderColor: '#008D49',
    borderRadius: 999,
    borderWidth: 2,
    height: 8,
    width: 8,
  },
  compactOrderRouteLine: {
    backgroundColor: 'rgba(0, 141, 73, 0.28)',
    borderRadius: 999,
    height: 18,
    width: 2,
  },
  compactOrderRouteMark: {
    alignItems: 'center',
    paddingTop: 5,
    width: 12,
  },
  compactOrderRouteRow: {
    flexDirection: 'row',
    gap: 10,
  },
  compactOrderTags: {
    alignItems: 'center',
    flexDirection: 'row',
    flexShrink: 1,
    gap: 6,
  },
  compactOrderTop: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
  },
  clientBrand: {
    color: '#12382C',
    fontSize: 24,
    fontWeight: '900',
    letterSpacing: 0,
  },
  clientBrandCopy: {
    flex: 1,
    minWidth: 0,
  },
  clientBrandMark: {
    alignItems: 'center',
    backgroundColor: '#008D49',
    borderRadius: 8,
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  clientBrandRow: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    gap: 10,
    minWidth: 0,
  },
  clientCallButton: {
    alignItems: 'center',
    backgroundColor: '#008D49',
    borderRadius: 16,
    elevation: 3,
    flex: 1,
    flexDirection: 'row',
    gap: 9,
    justifyContent: 'center',
    minHeight: 56,
    paddingHorizontal: 18,
    shadowColor: '#006F3A',
    shadowOffset: { height: 5, width: 0 },
    shadowOpacity: 0.18,
    shadowRadius: 10,
  },
  clientCallButtonDisabled: {
    opacity: 0.58,
  },
  clientCallButtonSimple: {
    minHeight: 82,
  },
  clientCallButtonText: {
    color: '#F4FAF6',
    fontSize: 19,
    fontWeight: '900',
  },
  clientCallButtonTextSimple: {
    fontSize: 25,
  },
  clientBackStepButton: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: 'rgba(18, 56, 44, 0.12)',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 7,
    justifyContent: 'center',
    minHeight: 56,
    minWidth: 108,
    paddingHorizontal: 14,
  },
  clientBackStepText: {
    color: '#008D49',
    fontSize: 15,
    fontWeight: '900',
  },
  clientDestinationBlock: {
    gap: 10,
    marginTop: 2,
  },
  clientDestinationInput: {
    backgroundColor: '#FFFFFF',
    borderColor: 'rgba(18, 56, 44, 0.16)',
    borderRadius: 8,
    borderWidth: 1,
    color: '#12382C',
    fontSize: 22,
    fontWeight: '800',
    minHeight: 62,
    paddingHorizontal: 16,
  },
  clientDestinationInputSimple: {
    fontSize: 32,
    minHeight: 92,
  },
  deliveryDetailsBlock: {
    backgroundColor: '#F7FBF8',
    borderColor: 'rgba(0, 141, 73, 0.16)',
    borderRadius: 8,
    borderWidth: 1,
    gap: 8,
    padding: 10,
  },
  deliveryCommentInput: {
    minHeight: 78,
    paddingVertical: 12,
    textAlignVertical: 'top',
  },
  deliveryDetailsHint: {
    alignItems: 'center',
    backgroundColor: '#E8F3EF',
    borderColor: 'rgba(0, 141, 73, 0.18)',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 9,
    minHeight: 54,
    padding: 12,
  },
  deliveryDetailsHintButton: {
    alignItems: 'center',
    backgroundColor: '#008D49',
    borderRadius: 8,
    justifyContent: 'center',
    minHeight: 38,
    paddingHorizontal: 12,
  },
  deliveryDetailsHintButtonText: {
    color: '#F4FAF6',
    fontSize: 12,
    fontWeight: '900',
  },
  deliveryDetailsHintText: {
    color: '#31584A',
    flex: 1,
    fontSize: 13,
    fontWeight: '800',
    lineHeight: 18,
  },
  deliveryDetailsMenu: {
    backgroundColor: '#FFFFFF',
    borderColor: 'rgba(18, 56, 44, 0.12)',
    borderRadius: 8,
    borderWidth: 1,
    gap: 9,
    padding: 12,
  },
  deliveryDetailsMenuHeader: {
    gap: 3,
  },
  deliveryDetailsMenuText: {
    color: '#557669',
    fontSize: 13,
    lineHeight: 18,
  },
  deliveryDetailsMenuTitle: {
    color: '#12382C',
    fontSize: 17,
    fontWeight: '900',
  },
  deliveryDetailsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  deliveryHandoffCard: {
    alignItems: 'flex-start',
    backgroundColor: '#FFFFFF',
    borderColor: 'rgba(18, 56, 44, 0.12)',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    minHeight: 76,
    padding: 12,
  },
  deliveryHandoffCardActive: {
    backgroundColor: '#008D49',
    borderColor: '#008D49',
  },
  deliveryHandoffCardCopy: {
    flex: 1,
    gap: 4,
    minWidth: 0,
  },
  deliveryHandoffCardDot: {
    backgroundColor: '#D6E8DF',
    borderColor: '#FFFFFF',
    borderRadius: 999,
    borderWidth: 2,
    height: 18,
    marginTop: 2,
    width: 18,
  },
  deliveryHandoffCardDotActive: {
    backgroundColor: '#F4FAF6',
  },
  deliveryHandoffCardText: {
    color: '#557669',
    fontSize: 12,
    fontWeight: '800',
    lineHeight: 17,
  },
  deliveryHandoffCardTextActive: {
    color: '#DDF1E7',
  },
  deliveryHandoffCardTitle: {
    color: '#12382C',
    fontSize: 15,
    fontWeight: '900',
  },
  deliveryHandoffCardTitleActive: {
    color: '#FFFFFF',
  },
  deliveryHandoffGrid: {
    gap: 8,
  },
  deliveryHandoffPanel: {
    backgroundColor: '#F7FBF8',
    borderColor: 'rgba(0, 141, 73, 0.16)',
    borderRadius: 8,
    borderWidth: 1,
    gap: 10,
    padding: 12,
  },
  deliveryHandoffPanelTitle: {
    color: '#12382C',
    fontSize: 18,
    fontWeight: '900',
  },
  deliveryHandoffButton: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: 'rgba(18, 56, 44, 0.14)',
    borderRadius: 8,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 42,
    paddingHorizontal: 10,
  },
  deliveryHandoffButtonActive: {
    backgroundColor: '#008D49',
    borderColor: '#008D49',
  },
  deliveryHandoffRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  deliveryHandoffText: {
    color: '#12382C',
    fontSize: 12,
    fontWeight: '900',
  },
  deliveryHandoffTextActive: {
    color: '#F4FAF6',
  },
  deliveryHalfInput: {
    flex: 1,
    fontSize: 16,
    minHeight: 54,
    minWidth: 150,
  },
  deliveryListInput: {
    fontSize: 17,
    minHeight: 86,
    paddingVertical: 12,
    textAlignVertical: 'top',
  },
  deliveryPresetButton: {
    backgroundColor: '#FFFFFF',
    borderColor: 'rgba(18, 56, 44, 0.12)',
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    gap: 3,
    minHeight: 58,
    minWidth: 120,
    paddingHorizontal: 10,
    paddingVertical: 9,
  },
  deliveryPresetButtonActive: {
    backgroundColor: '#E8F3EF',
    borderColor: '#008D49',
  },
  deliveryPresetGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  deliveryPresetText: {
    color: '#557669',
    fontSize: 11,
    fontWeight: '800',
  },
  deliveryPresetTextActive: {
    color: '#1B5F47',
  },
  deliveryPresetTitle: {
    color: '#12382C',
    fontSize: 13,
    fontWeight: '900',
  },
  deliveryPresetTitleActive: {
    color: '#008D49',
  },
  deliveryStepPanel: {
    gap: 10,
  },
  clientInlineActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  clientRemoveStopButton: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: 'rgba(193, 122, 112, 0.34)',
    borderRadius: 8,
    borderWidth: 1,
    height: 50,
    justifyContent: 'center',
    width: 50,
  },
  clientRemoveStopText: {
    color: '#C17A70',
    fontSize: 24,
    fontWeight: '900',
    lineHeight: 26,
  },
  clientScheduleInput: {
    backgroundColor: '#FFFFFF',
    borderColor: 'rgba(18, 56, 44, 0.16)',
    borderRadius: 8,
    borderWidth: 1,
    color: '#12382C',
    flex: 1,
    fontSize: 15,
    fontWeight: '800',
    minHeight: 50,
    minWidth: 210,
    paddingHorizontal: 12,
  },
  clientSmallOptionButton: {
    alignItems: 'center',
    backgroundColor: '#E8F3EF',
    borderColor: '#008D49',
    borderRadius: 8,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 50,
    paddingHorizontal: 12,
  },
  clientSmallOptionButtonMuted: {
    opacity: 0.48,
  },
  clientSmallOptionText: {
    color: '#008D49',
    fontSize: 13,
    fontWeight: '900',
  },
  clientStopInput: {
    flex: 1,
    fontSize: 17,
    minHeight: 50,
  },
  clientStopRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  clientError: {
    color: '#FF3B30',
    fontSize: 14,
    fontWeight: '800',
  },
  clientFlowCopy: {
    flex: 1,
    gap: 5,
    minWidth: 0,
  },
  clientFlowHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
  },
  clientFlowIcon: {
    alignItems: 'center',
    backgroundColor: 'rgba(0, 168, 85, 0.1)',
    borderColor: 'rgba(0, 168, 85, 0.2)',
    borderRadius: 8,
    borderWidth: 1,
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  clientFlowMap: {
    backgroundColor: '#DDECE3',
    borderColor: 'rgba(18, 56, 44, 0.1)',
    borderRadius: 8,
    borderWidth: 1,
    height: 82,
    overflow: 'hidden',
  },
  clientFlowPanel: {
    backgroundColor: '#EEF7F1',
    borderColor: 'rgba(18, 56, 44, 0.12)',
    borderRadius: 8,
    borderWidth: 1,
    gap: 12,
    padding: 13,
  },
  clientFlowText: {
    color: '#557669',
    fontSize: 13,
    lineHeight: 18,
  },
  clientFlowTitle: {
    color: '#12382C',
    fontSize: 18,
    fontWeight: '900',
  },
  clientInputDot: {
    backgroundColor: '#008D49',
    borderRadius: 999,
    height: 9,
    width: 9,
  },
  clientInputDotEnd: {
    backgroundColor: '#FFFFFF',
    borderColor: '#008D49',
    borderWidth: 2,
  },
  clientInputLabel: {
    color: '#31584A',
    fontSize: 12,
    fontWeight: '900',
  },
  clientInputLabelRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 7,
  },
  clientInputShell: {
    gap: 6,
  },
  clientMapCar: {
    alignItems: 'center',
    backgroundColor: '#B7F46A',
    borderColor: 'rgba(255, 255, 255, 0.7)',
    borderRadius: 999,
    borderWidth: 2,
    height: 30,
    justifyContent: 'center',
    width: 30,
  },
  clientMapPointStart: {
    backgroundColor: '#40C878',
    borderColor: '#DFFFD0',
    borderRadius: 999,
    borderWidth: 2,
    height: 16,
    width: 16,
  },
  clientMapRoadThin: {
    backgroundColor: 'rgba(18, 56, 44, 0.08)',
    borderRadius: 999,
    height: 3,
    left: -16,
    position: 'absolute',
    right: 24,
    top: 54,
    transform: [{ rotate: '-10deg' }],
  },
  clientMapRoadWide: {
    backgroundColor: 'rgba(18, 56, 44, 0.07)',
    borderRadius: 999,
    height: 9,
    left: 18,
    position: 'absolute',
    right: -26,
    top: 27,
    transform: [{ rotate: '15deg' }],
  },
  clientMapRoute: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    left: 20,
    position: 'absolute',
    right: 18,
    top: 30,
  },
  clientMapRouteLine: {
    backgroundColor: '#00A855',
    borderRadius: 999,
    flex: 1,
    height: 4,
  },
  clientOptionalToggle: {
    alignItems: 'center',
    backgroundColor: '#E8F3EF',
    borderColor: 'rgba(0, 141, 73, 0.18)',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: 46,
    paddingHorizontal: 12,
  },
  clientOptionalToggleMeta: {
    color: '#557669',
    fontSize: 12,
    fontWeight: '800',
  },
  clientOptionalToggleText: {
    color: '#008D49',
    flex: 1,
    fontSize: 14,
    fontWeight: '900',
  },
  clientScenePoint: {
    color: '#31584A',
    flex: 1,
    fontSize: 12,
    fontWeight: '800',
  },
  clientSceneSummary: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  clientProgressFill: {
    backgroundColor: '#008D49',
    borderRadius: 999,
    height: '100%',
  },
  clientProgressTrack: {
    backgroundColor: '#E8F3EF',
    borderRadius: 999,
    height: 7,
    overflow: 'hidden',
  },
  clientStepBody: {
    gap: 14,
  },
  clientStepPill: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#D6E8DF',
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    minHeight: 34,
    minWidth: 92,
    justifyContent: 'center',
    paddingHorizontal: 8,
  },
  clientStepPillActive: {
    backgroundColor: '#008D49',
    borderColor: '#008D49',
  },
  clientStepPillDone: {
    backgroundColor: '#E8F3EF',
    borderColor: '#BFDACE',
  },
  clientStepRail: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  clientStepText: {
    color: '#557669',
    fontSize: 12,
    fontWeight: '900',
  },
  clientStepTextActive: {
    color: '#FFFFFF',
  },
  clientStepTextDone: {
    color: '#008D49',
  },
  clientSummaryCard: {
    backgroundColor: '#FFFFFF',
    borderColor: '#D6E8DF',
    borderRadius: 8,
    borderWidth: 1,
    gap: 12,
    padding: 14,
  },
  clientSummaryLabel: {
    color: '#557669',
    fontSize: 12,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  clientSummaryRow: {
    borderBottomColor: '#E2EFE8',
    borderBottomWidth: 1,
    gap: 4,
    paddingBottom: 10,
  },
  clientSummaryTitle: {
    color: '#12382C',
    fontSize: 20,
    fontWeight: '900',
  },
  clientSummaryTotalLabel: {
    color: '#12382C',
    fontSize: 14,
    fontWeight: '900',
  },
  clientSummaryTotalRow: {
    alignItems: 'center',
    borderBottomWidth: 0,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingBottom: 0,
  },
  clientSummaryTotalValue: {
    color: '#008D49',
    fontSize: 24,
    fontWeight: '900',
  },
  clientSummaryValue: {
    color: '#12382C',
    fontSize: 15,
    fontWeight: '800',
    lineHeight: 20,
  },
  clientCompactDetails: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  clientDetailItem: {
    backgroundColor: '#FFFFFF',
    borderColor: '#D6E8DF',
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    gap: 3,
    justifyContent: 'center',
    minHeight: 48,
    minWidth: 112,
    paddingHorizontal: 11,
    paddingVertical: 8,
  },
  clientDetailLabel: {
    color: '#557669',
    fontSize: 11,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  clientDetailStatus: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 7,
    minWidth: 156,
  },
  clientDetailStatusText: {
    color: '#557669',
    flex: 1,
    fontSize: 13,
    fontWeight: '800',
  },
  clientDetailValue: {
    color: '#12382C',
    fontSize: 14,
    fontWeight: '800',
  },
  clientMeta: {
    color: '#557669',
    fontSize: 13,
    fontWeight: '800',
    marginTop: 2,
  },
  clientModeButton: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#008D49',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    minHeight: 44,
    paddingHorizontal: 12,
  },
  clientModeText: {
    color: '#008D49',
    fontSize: 13,
    fontWeight: '900',
  },
  clientScroll: {
    backgroundColor: '#F6F8F5',
    flex: 1,
  },
  serviceSwitch: {
    backgroundColor: '#FFFFFF',
    borderColor: 'rgba(18, 56, 44, 0.1)',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    padding: 6,
  },
  serviceSwitchButton: {
    alignItems: 'center',
    borderRadius: 8,
    flex: 1,
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'center',
    minHeight: 48,
    paddingHorizontal: 10,
  },
  serviceSwitchButtonActive: {
    backgroundColor: '#008D49',
  },
  serviceSwitchTitle: {
    color: '#008D49',
    fontSize: 14,
    fontWeight: '900',
  },
  serviceSwitchTitleActive: {
    color: '#F4FAF6',
  },
  clientPage: {
    backgroundColor: '#F6F8F5',
    flexGrow: 1,
  },
  orderScene: {
    backgroundColor: '#DDECE3',
    height: 280,
    position: 'relative',
  },
  orderSceneShade: {
    backgroundColor: 'rgba(10, 20, 17, 0.10)',
    bottom: 0,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  orderSceneTop: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 11,
    left: 0,
    paddingHorizontal: 16,
    paddingTop: 16,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  orderSceneBack: {
    alignItems: 'center',
    backgroundColor: 'rgba(10, 20, 17, 0.72)',
    borderColor: 'rgba(92, 230, 160, 0.25)',
    borderRadius: 13,
    borderWidth: 1,
    height: 42,
    justifyContent: 'center',
    width: 42,
  },
  orderSceneTitle: {
    color: '#F2FBF6',
    flex: 1,
    fontSize: 18,
    fontWeight: '800',
    letterSpacing: -0.4,
    textShadowColor: 'rgba(10, 20, 17, 0.55)',
    textShadowOffset: { height: 1, width: 0 },
    textShadowRadius: 8,
  },
  orderSceneAa: {
    alignItems: 'center',
    backgroundColor: 'rgba(10, 20, 17, 0.72)',
    borderColor: 'rgba(92, 230, 160, 0.25)',
    borderRadius: 13,
    borderWidth: 1,
    height: 42,
    justifyContent: 'center',
    width: 42,
  },
  orderSceneAaOn: {
    backgroundColor: '#B7F46A',
    borderColor: '#B7F46A',
  },
  orderSceneAaText: {
    color: '#B7F46A',
    fontSize: 15,
    fontWeight: '800',
  },
  orderSceneAaTextOn: {
    color: '#0A1411',
  },
  orderSceneCars: {
    alignItems: 'center',
    backgroundColor: 'rgba(10, 20, 17, 0.72)',
    borderRadius: 999,
    flexDirection: 'row',
    gap: 7,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  orderSceneCarsDot: {
    backgroundColor: '#B7F46A',
    borderRadius: 4,
    height: 8,
    width: 8,
  },
  orderSceneCarsText: {
    color: '#5CE6A0',
    fontSize: 12,
    fontWeight: '800',
  },
  orderSheet: {
    backgroundColor: '#F6F8F5',
    borderTopLeftRadius: 26,
    borderTopRightRadius: 26,
    flexGrow: 1,
    gap: 13,
    marginTop: -24,
    padding: 16,
    paddingTop: 12,
  },
  orderSheetGrab: {
    alignSelf: 'center',
    backgroundColor: 'rgba(11, 47, 37, 0.14)',
    borderRadius: 3,
    height: 5,
    width: 44,
  },
  orderLocateChip: {
    alignItems: 'center',
    backgroundColor: 'rgba(0, 141, 73, 0.10)',
    borderRadius: 999,
    flexDirection: 'row',
    gap: 5,
    marginLeft: 'auto',
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  orderLocateChipText: {
    color: '#008D49',
    fontSize: 11,
    fontWeight: '800',
  },
  orderWhenRow: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  orderWhenLabel: {
    color: '#71877D',
    fontSize: 12,
    fontWeight: '700',
  },
  orderWhenChip: {
    backgroundColor: '#FFFFFF',
    borderColor: 'rgba(11, 47, 37, 0.10)',
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 13,
    paddingVertical: 9,
  },
  orderWhenChipOn: {
    backgroundColor: '#0B6B4A',
    borderColor: '#0B6B4A',
  },
  orderWhenChipText: {
    color: '#12382C',
    fontSize: 12,
    fontWeight: '800',
  },
  orderWhenChipTextOn: {
    color: '#F4FAF6',
  },
  orderPriceCard: {
    backgroundColor: '#FFFFFF',
    borderColor: 'rgba(11, 47, 37, 0.10)',
    borderRadius: 18,
    borderWidth: 1,
    gap: 7,
    padding: 16,
    shadowColor: '#0B2F25',
    shadowOffset: { height: 10, width: 0 },
    shadowOpacity: 0.05,
    shadowRadius: 20,
  },
  orderPriceRow: {
    alignItems: 'baseline',
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'space-between',
  },
  orderPriceName: {
    color: '#12382C',
    flexShrink: 1,
    fontSize: 15,
    fontWeight: '800',
  },
  orderPriceValue: {
    color: '#12382C',
    fontSize: 26,
    fontWeight: '800',
    letterSpacing: -0.5,
  },
  orderPriceMeta: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'space-between',
  },
  orderBonusRow: {
    alignItems: 'center',
    backgroundColor: '#F7FBF8',
    borderColor: 'rgba(0, 141, 73, 0.16)',
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 9,
    marginTop: 3,
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  orderBonusRowActive: {
    backgroundColor: 'rgba(183, 244, 106, 0.16)',
    borderColor: 'rgba(0, 141, 73, 0.35)',
  },
  orderBonusDot: {
    alignItems: 'center',
    borderColor: 'rgba(11, 47, 37, 0.25)',
    borderRadius: 6,
    borderWidth: 1.5,
    height: 18,
    justifyContent: 'center',
    width: 18,
  },
  orderBonusDotActive: {
    backgroundColor: '#008D49',
    borderColor: '#008D49',
  },
  orderBonusDotMark: {
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: '800',
    lineHeight: 13,
  },
  orderBonusText: {
    color: '#12382C',
    flexShrink: 1,
    fontSize: 13,
    fontWeight: '700',
  },
  orderBonusTextActive: {
    color: '#0B6B4A',
  },
  orderPriceMetaText: {
    color: '#71877D',
    fontSize: 12,
    fontWeight: '600',
  },
  orderPriceLive: {
    alignItems: 'center',
    flexDirection: 'row',
    flexShrink: 1,
    gap: 6,
  },
  orderBottomBar: {
    backgroundColor: 'rgba(246, 248, 245, 0.98)',
    borderTopColor: 'rgba(11, 47, 37, 0.08)',
    borderTopWidth: 1,
    gap: 8,
    paddingBottom: 18,
    paddingHorizontal: 16,
    paddingTop: 12,
  },
  clientPageSimple: {},
  clientRealtime: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: 'rgba(18, 56, 44, 0.1)',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    minHeight: 38,
    paddingHorizontal: 11,
    paddingVertical: 8,
  },
  clientRealtimeDot: {
    backgroundColor: '#557669',
    borderRadius: 5,
    height: 10,
    width: 10,
  },
  clientRealtimeDotLive: {
    backgroundColor: '#008D49',
  },
  clientRealtimeText: {
    color: '#557669',
    flex: 1,
    fontSize: 12,
    fontWeight: '800',
  },
  clientSafeArea: {
    backgroundColor: '#F6F8F5',
    flex: 1,
  },
  clientShortcutButton: {
    alignItems: 'flex-start',
    backgroundColor: '#FFFFFF',
    borderColor: 'rgba(18, 56, 44, 0.1)',
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    gap: 3,
    justifyContent: 'center',
    minHeight: 46,
    paddingHorizontal: 12,
  },
  clientShortcutButtonSimple: {
    minHeight: 70,
  },
  clientShortcutRow: {
    flexDirection: 'row',
    gap: 10,
  },
  clientShortcutHint: {
    color: '#557669',
    flexShrink: 1,
    fontSize: 12,
    lineHeight: 16,
  },
  clientShortcutText: {
    color: '#12382C',
    fontSize: 16,
    fontWeight: '900',
  },
  clientShortcutTextSimple: {
    fontSize: 21,
  },
  clientSuggestion: {
    backgroundColor: '#E8F3EF',
    borderRadius: 8,
    gap: 3,
    padding: 10,
  },
  clientSuggestionText: {
    color: '#557669',
    fontSize: 12,
  },
  clientSuggestionTitle: {
    color: '#12382C',
    fontSize: 14,
    fontWeight: '900',
  },
  clientSuggestions: {
    backgroundColor: '#FFFFFF',
    borderColor: 'rgba(18, 56, 44, 0.1)',
    borderRadius: 8,
    borderWidth: 1,
    gap: 8,
    padding: 8,
  },
  clientTariffCard: {
    backgroundColor: '#FFFFFF',
    borderColor: 'rgba(18, 56, 44, 0.1)',
    borderRadius: 8,
    borderWidth: 1,
    gap: 16,
    minHeight: 154,
    padding: 15,
    shadowColor: '#12382C',
    shadowOffset: { height: 3, width: 0 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
  },
  clientTariffCardActive: {
    backgroundColor: '#FFFFFF',
    borderColor: '#008D49',
    borderWidth: 1.5,
    elevation: 3,
  },
  clientTariffList: {
    gap: 8,
    paddingVertical: 2,
  },
  clientResetButton: {
    alignItems: 'center',
    backgroundColor: '#E8F3EF',
    borderColor: 'rgba(18, 56, 44, 0.08)',
    borderRadius: 8,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 34,
    paddingHorizontal: 12,
  },
  clientResetButtonText: {
    color: '#C0392B',
    fontSize: 12,
    fontWeight: '900',
  },
  clientSheetHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'space-between',
  },
  clientSheetTitle: {
    color: '#12382C',
    flex: 1,
    fontSize: 20,
    fontWeight: '900',
    minWidth: 0,
  },
  clientTariffBadge: {
    alignItems: 'center',
    backgroundColor: '#E8F3EF',
    borderColor: '#BFDACE',
    borderRadius: 8,
    borderWidth: 1,
    minHeight: 28,
    paddingHorizontal: 10,
    justifyContent: 'center',
  },
  clientTariffBadgeText: {
    color: '#008D49',
    fontSize: 12,
    fontWeight: '900',
  },
  clientTariffBenefit: {
    alignItems: 'center',
    backgroundColor: '#F4FAF6',
    borderColor: '#D6E8DF',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 6,
    minHeight: 28,
    paddingHorizontal: 9,
  },
  clientTariffBenefitDot: {
    backgroundColor: '#008D49',
    borderRadius: 3,
    height: 6,
    width: 6,
  },
  clientTariffBenefitText: {
    color: '#31584A',
    fontSize: 12,
    fontWeight: '800',
  },
  clientTariffBenefits: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 7,
    marginTop: 10,
  },
  clientTariffCopy: {
    flex: 1,
    minWidth: 0,
  },
  clientTariffConfidence: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  clientTariffConfidenceText: {
    backgroundColor: '#FFFFFF',
    borderColor: 'rgba(0, 141, 73, 0.18)',
    borderRadius: 999,
    borderWidth: 1,
    color: '#006F3A',
    fontSize: 11,
    fontWeight: '900',
    overflow: 'hidden',
    paddingHorizontal: 8,
    paddingVertical: 5,
  },
  clientTariffHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  clientTariffMainRow: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
  },
  clientTariffPrice: {
    color: '#12382C',
    fontSize: 25,
    fontWeight: '800',
    lineHeight: 31,
    textAlign: 'right',
  },
  clientTariffPriceActive: {
    color: '#12382C',
  },
  clientTariffRouteDot: {
    backgroundColor: '#008D49',
    borderRadius: 4,
    height: 8,
    width: 8,
  },
  clientTariffRouteLine: {
    backgroundColor: '#BFDACE',
    height: 2,
    width: 34,
  },
  clientTariffSubtitle: {
    color: '#557669',
    fontSize: 12,
    lineHeight: 17,
  },
  clientTariffSubtitleActive: {
    color: '#557669',
  },
  clientTariffTitle: {
    color: '#12382C',
    fontSize: 22,
    fontWeight: '900',
    lineHeight: 27,
  },
  clientTariffTitleActive: {
    color: '#12382C',
  },
  clientTariffVisual: {
    alignItems: 'center',
    backgroundColor: '#F4FAF6',
    borderColor: '#D6E8DF',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 7,
    minHeight: 30,
    paddingHorizontal: 10,
  },
  clientTripEta: {
    color: '#008D49',
    fontSize: 13,
    fontWeight: '900',
  },
  clientTripHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'space-between',
  },
  clientTripTitle: {
    color: '#12382C',
    flex: 1,
    fontSize: 18,
    fontWeight: '900',
    minWidth: 0,
  },
  clientTopRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  addressSuggestion: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#008D49',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    padding: 11,
  },
  addressSuggestionCopy: {
    flex: 1,
    gap: 3,
    minWidth: 0,
  },
  addressSuggestionDot: {
    backgroundColor: '#008D49',
    borderRadius: 6,
    height: 10,
    width: 10,
  },
  addressSuggestionSettlement: {
    color: '#008D49',
    fontSize: 11,
    fontWeight: '900',
  },
  addressSuggestions: {
    backgroundColor: '#E8F3EF',
    borderColor: '#008D49',
    borderRadius: 8,
    borderWidth: 1,
    gap: 8,
    padding: 8,
  },
  addressSuggestionSubtitle: {
    color: '#557669',
    fontSize: 12,
    lineHeight: 17,
  },
  addressSuggestionTitle: {
    color: '#12382C',
    fontSize: 14,
    fontWeight: '900',
  },
  backButton: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#008D49',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    minHeight: 42,
    paddingHorizontal: 12,
  },
  backButtonText: {
    color: '#008D49',
    fontSize: 14,
    fontWeight: '900',
  },
  disabledButton: {
    opacity: 0.55,
  },
  detailsLabel: {
    color: '#557669',
    fontSize: 12,
    fontWeight: '600',
    width: 92,
  },
  detailsList: {
    gap: 10,
  },
  detailsRow: {
    alignItems: 'flex-start',
    borderBottomColor: '#E8F3EF',
    borderBottomWidth: 1,
    flexDirection: 'row',
    gap: 10,
    paddingBottom: 10,
  },
  detailsSheet: {
    backgroundColor: '#F4FAF6',
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
    gap: 14,
    maxHeight: '82%',
    padding: 16,
  },
  detailsSheetHandle: {
    alignSelf: 'center',
    backgroundColor: 'rgba(18, 56, 44, 0.24)',
    borderRadius: 99,
    height: 4,
    width: 44,
  },
  detailsSheetHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
  },
  detailsSheetRoot: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  detailsSheetScrim: {
    backgroundColor: 'rgba(18, 56, 44, 0.34)',
    flex: 1,
  },
  detailsSheetSubtitle: {
    color: '#557669',
    fontSize: 13,
    fontWeight: '600',
  },
  detailsSheetTitle: {
    color: '#12382C',
    fontSize: 20,
    fontWeight: '700',
  },
  detailsSheetTitleCopy: {
    flex: 1,
    gap: 3,
    minWidth: 0,
  },
  detailsValue: {
    color: '#12382C',
    flex: 1,
    fontSize: 14,
    fontWeight: '600',
    lineHeight: 20,
    textAlign: 'right',
  },
  feedRefreshButton: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: 'rgba(0, 141, 73, 0.28)',
    borderRadius: 8,
    borderWidth: 1,
    height: 40,
    justifyContent: 'center',
    width: 44,
  },
  feedSortButton: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: 'rgba(0, 141, 73, 0.22)',
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    justifyContent: 'center',
    minHeight: 40,
    paddingHorizontal: 10,
  },
  feedSortButtonActive: {
    backgroundColor: '#008D49',
    borderColor: '#008D49',
  },
  feedSortButtonText: {
    color: '#008D49',
    fontSize: 13,
    fontWeight: '700',
  },
  feedSortButtonTextActive: {
    color: '#F4FAF6',
  },
  feedToolbar: {
    flexDirection: 'row',
    gap: 8,
  },
  field: {
    gap: 8,
  },
  fields: {
    gap: 14,
  },
  groupLabel: {
    color: '#12382C',
    fontSize: 14,
    fontWeight: '900',
  },
  helper: {
    color: '#557669',
    fontSize: 12,
    lineHeight: 17,
  },
  infoButton: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: 'rgba(0, 141, 73, 0.28)',
    borderRadius: 8,
    borderWidth: 1,
    height: 46,
    justifyContent: 'center',
    width: 46,
  },
  infoButtonText: {
    color: '#008D49',
    fontSize: 24,
    fontWeight: '600',
    lineHeight: 26,
  },
  hiddenClientButtonLabel: {
    display: 'none',
  },
  hero: {
    alignItems: 'flex-start',
    backgroundColor: '#FFFFFF',
    borderColor: '#008D49',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    padding: 12,
  },
  heroCopy: {
    flex: 1,
    gap: 7,
    minWidth: 0,
  },
  heroIcon: {
    alignItems: 'center',
    backgroundColor: '#E8F3EF',
    borderRadius: 8,
    height: 46,
    justifyContent: 'center',
    width: 46,
  },
  homeAddressButton: {
    backgroundColor: '#FFFFFF',
    borderColor: '#008D49',
    borderRadius: 8,
    borderWidth: 1,
    gap: 3,
    padding: 10,
  },
  homeAddressText: {
    color: '#557669',
    fontSize: 12,
    lineHeight: 17,
  },
  homeAddressTitle: {
    color: '#008D49',
    fontSize: 13,
    fontWeight: '900',
  },
  input: {
    backgroundColor: '#FFFFFF',
    borderColor: 'rgba(18, 56, 44, 0.16)',
    borderRadius: 8,
    borderWidth: 1,
    color: '#12382C',
    fontSize: 16,
    fontWeight: '600',
    minHeight: 56,
    paddingHorizontal: 14,
  },
  label: {
    color: '#12382C',
    fontSize: 14,
    fontWeight: '900',
  },
  layout: {
    gap: 16,
  },
  layoutWide: {
    alignItems: 'flex-start',
    flexDirection: 'row',
  },
  locationButton: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: 'rgba(0, 141, 73, 0.28)',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'center',
    minHeight: 42,
    paddingHorizontal: 12,
  },
  locationButtonText: {
    color: '#008D49',
    fontSize: 13,
    fontWeight: '900',
  },
  mainColumn: {
    flex: 1,
    gap: 16,
    minWidth: 0,
  },
  optionButton: {
    alignItems: 'center',
    backgroundColor: '#F7FBF8',
    borderColor: 'rgba(18, 56, 44, 0.12)',
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    flexDirection: 'row',
    gap: 10,
    minHeight: 58,
    minWidth: 180,
    padding: 12,
  },
  optionButtonActive: {
    backgroundColor: '#F1F8F3',
    borderColor: '#008D49',
  },
  optionCheck: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#008D49',
    borderRadius: 6,
    borderWidth: 1.5,
    height: 24,
    justifyContent: 'center',
    width: 24,
  },
  optionCheckActive: {
    backgroundColor: '#008D49',
    borderColor: '#008D49',
  },
  optionCopy: {
    flex: 1,
    gap: 3,
    minWidth: 0,
  },
  optionGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  optionLabel: {
    color: '#12382C',
    fontSize: 14,
    fontWeight: '900',
  },
  optionPrice: {
    color: '#557669',
    fontSize: 12,
    lineHeight: 16,
  },
  offerNotice: {
    backgroundColor: '#FFFFFF',
    borderColor: '#008D49',
    borderRadius: 8,
    borderWidth: 1,
    gap: 8,
    padding: 12,
  },
  offerNoticeText: {
    color: '#557669',
    fontSize: 13,
    lineHeight: 18,
  },
  offerNoticeTitle: {
    color: '#12382C',
    fontSize: 14,
    fontWeight: '900',
  },
  driverFeedEmptyBox: {
    backgroundColor: '#EEF8F1',
    borderColor: 'rgba(0, 141, 73, 0.18)',
    borderRadius: 8,
    borderWidth: 1,
    gap: 5,
    padding: 14,
  },
  driverFeedEmptyText: {
    color: '#557669',
    fontSize: 13,
    lineHeight: 18,
  },
  driverFeedEmptyTitle: {
    color: '#12382C',
    fontSize: 15,
    fontWeight: '900',
  },
  driverFeedHeaderCopy: {
    flex: 1,
    gap: 4,
    minWidth: 0,
  },
  driverFeedHeaderIcon: {
    alignItems: 'center',
    backgroundColor: '#E8F3EF',
    borderRadius: 8,
    height: 42,
    justifyContent: 'center',
    width: 42,
  },
  driverFeedHeaderPanel: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: 'rgba(0, 141, 73, 0.2)',
    borderRadius: 8,
    borderWidth: 1,
    elevation: 2,
    flexDirection: 'row',
    gap: 10,
    padding: 12,
    shadowColor: 'rgba(18, 56, 44, 0.18)',
    shadowOffset: { height: 3, width: 0 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
  },
  driverFeedListCopy: {
    flex: 1,
    gap: 3,
    minWidth: 0,
  },
  driverFeedListPanel: {
    backgroundColor: '#FFFFFF',
    borderColor: 'rgba(0, 141, 73, 0.2)',
    borderRadius: 8,
    borderWidth: 1,
    elevation: 2,
    gap: 10,
    padding: 12,
    shadowColor: 'rgba(18, 56, 44, 0.18)',
    shadowOffset: { height: 3, width: 0 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
  },
  driverFeedListTop: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
  },
  driverFeedPage: {
    backgroundColor: '#F6F8F5',
    gap: 14,
    minHeight: '100%',
    padding: 14,
  },
  driverFeedScreenText: {
    color: '#557669',
    fontSize: 13,
    lineHeight: 18,
  },
  driverFeedScreenTitle: {
    color: '#12382C',
    fontSize: 20,
    fontWeight: '900',
  },
  page: {
    backgroundColor: '#F6F8F5',
    gap: 14,
    minHeight: '100%',
    padding: 14,
  },
  panel: {
    backgroundColor: '#FFFFFF',
    borderColor: 'rgba(18, 56, 44, 0.12)',
    borderRadius: 8,
    borderWidth: 1,
    elevation: 1,
    gap: 12,
    padding: 12,
    shadowColor: 'rgba(18, 56, 44, 0.14)',
    shadowOffset: { height: 3, width: 0 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
  },
  paymentButton: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: 'rgba(18, 56, 44, 0.12)',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 9,
    minHeight: 44,
    paddingHorizontal: 12,
  },
  paymentButtonActive: {
    backgroundColor: '#008D49',
    borderColor: '#008D49',
  },
  paymentGroup: {
    gap: 9,
  },
  paymentText: {
    color: '#12382C',
    flex: 1,
    fontSize: 14,
    fontWeight: '900',
  },
  paymentTextActive: {
    color: '#F4FAF6',
  },
  pressed: {
    opacity: 0.92,
    transform: [{ scale: 0.98 }],
  },
  primaryButton: {
    alignItems: 'center',
    backgroundColor: '#008D49',
    borderRadius: 8,
    elevation: 2,
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'center',
    minHeight: 56,
    paddingHorizontal: 16,
    shadowColor: 'rgba(0, 111, 58, 0.22)',
    shadowOffset: { height: 7, width: 0 },
    shadowOpacity: 0.14,
    shadowRadius: 14,
  },
  primaryButtonText: {
    color: '#F4FAF6',
    fontSize: 15,
    fontWeight: '900',
    textAlign: 'center',
  },
  resultBox: {
    backgroundColor: '#F1F8F3',
    borderColor: 'rgba(0, 141, 73, 0.28)',
    borderRadius: 8,
    borderWidth: 1,
    gap: 5,
    padding: 12,
  },
  resultBoxSuccess: {
    backgroundColor: '#E8F3EF',
    borderColor: '#7A9A7E',
  },
  resultText: {
    color: '#557669',
    fontSize: 12,
    lineHeight: 17,
  },
  resultTitle: {
    color: '#12382C',
    fontSize: 14,
    fontWeight: '900',
  },
  searchCarsBox: {
    backgroundColor: '#E8F3EF',
    borderColor: '#008D49',
    borderRadius: 8,
    borderWidth: 1,
    gap: 6,
    padding: 12,
  },
  searchCarsBoxEmpty: {
    backgroundColor: '#E8F3EF',
    borderColor: '#C17A70',
  },
  searchCarsBoxReady: {
    backgroundColor: '#E8F3EF',
    borderColor: '#7A9A7E',
  },
  searchCarsText: {
    color: '#557669',
    fontSize: 13,
    lineHeight: 19,
  },
  searchCarsTitle: {
    color: '#12382C',
    flex: 1,
    fontSize: 15,
    fontWeight: '900',
  },
  searchCarsTop: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  searchCarsValue: {
    color: '#008D49',
    fontSize: 22,
    fontWeight: '900',
  },
  regionBox: {
    backgroundColor: '#FFFFFF',
    borderColor: '#008D49',
    borderRadius: 8,
    borderWidth: 1,
    gap: 5,
    padding: 12,
  },
  regionLine: {
    color: '#008D49',
    fontSize: 13,
    fontWeight: '800',
    lineHeight: 18,
  },
  regionMeta: {
    color: '#008D49',
    fontSize: 12,
    fontWeight: '900',
  },
  regionText: {
    color: '#557669',
    fontSize: 13,
    lineHeight: 19,
  },
  regionTitle: {
    color: '#008D49',
    fontSize: 14,
    fontWeight: '900',
  },
  rolePill: {
    alignItems: 'center',
    backgroundColor: '#E8F3EF',
    borderRadius: 8,
    flexDirection: 'row',
    gap: 7,
    minHeight: 42,
    paddingHorizontal: 12,
  },
  rolePillText: {
    color: '#008D49',
    fontSize: 13,
    fontWeight: '900',
  },
  routeEstimateBody: {
    alignItems: 'stretch',
    flexDirection: 'row',
    gap: 10,
  },
  routeEstimateBox: {
    backgroundColor: '#E8F3EF',
    borderRadius: 8,
    gap: 12,
    padding: 12,
  },
  routeEstimateHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  routeEstimateTitle: {
    color: '#008D49',
    fontSize: 13,
    fontWeight: '900',
  },
  routeMetric: {
    flex: 1,
    gap: 3,
    minWidth: 80,
  },
  routeMetricLabel: {
    color: '#557669',
    fontSize: 11,
    lineHeight: 15,
  },
  routeMetricValue: {
    color: '#12382C',
    fontSize: 14,
    fontWeight: '900',
  },
  routeMetrics: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  priceConfidenceChip: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: 'rgba(0, 141, 73, 0.16)',
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 6,
    paddingHorizontal: 9,
    paddingVertical: 6,
  },
  priceConfidenceRail: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 7,
  },
  priceConfidenceText: {
    color: '#006F3A',
    fontSize: 11,
    fontWeight: '900',
  },
  routePointText: {
    color: '#557669',
    fontSize: 12,
    lineHeight: 17,
  },
  routePointTitle: {
    color: '#12382C',
    fontSize: 13,
    fontWeight: '900',
    lineHeight: 18,
  },
  routePoints: {
    flex: 1,
    gap: 7,
    minWidth: 0,
  },
  routePresetCard: {
    backgroundColor: '#FFFFFF',
    borderColor: 'rgba(18, 56, 44, 0.1)',
    borderRadius: 8,
    borderWidth: 1,
    elevation: 1,
    flex: 1,
    gap: 7,
    minWidth: 185,
    padding: 12,
    shadowColor: 'rgba(18, 56, 44, 0.12)',
    shadowOffset: { height: 3, width: 0 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
  },
  routePresetGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  routePresetMeta: {
    color: '#008D49',
    fontSize: 12,
    fontWeight: '900',
  },
  routePresetSubtitle: {
    color: '#557669',
    fontSize: 12,
    lineHeight: 17,
  },
  routePresetTitle: {
    color: '#12382C',
    flex: 1,
    fontSize: 14,
    fontWeight: '900',
  },
  routePresetTop: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  routeTrack: {
    alignItems: 'center',
    width: 16,
  },
  routeTrackDot: {
    backgroundColor: '#008D49',
    borderRadius: 5,
    height: 10,
    width: 10,
  },
  routeTrackDotFinish: {
    backgroundColor: '#5C8D89',
  },
  routeTrackLine: {
    backgroundColor: '#008D49',
    flex: 1,
    marginVertical: 3,
    width: 2,
  },
  safeArea: {
    backgroundColor: '#F4FAF6',
    flex: 1,
  },
  secondaryButton: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: 'rgba(0, 141, 73, 0.28)',
    borderRadius: 8,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 48,
    paddingHorizontal: 16,
  },
  secondaryButtonText: {
    color: '#12382C',
    fontSize: 14,
    fontWeight: '900',
  },
  skipOfferButton: {
    alignItems: 'center',
    backgroundColor: '#F1F8F3',
    borderColor: 'rgba(0, 141, 73, 0.28)',
    borderRadius: 8,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 42,
    paddingHorizontal: 12,
  },
  skipOfferButtonText: {
    color: '#12382C',
    fontSize: 14,
    fontWeight: '900',
  },
  sectionHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  sectionTitle: {
    color: '#12382C',
    flex: 1,
    fontSize: 18,
    fontWeight: '900',
  },
  statusBox: {
    alignItems: 'flex-start',
    backgroundColor: '#E8F3EF',
    borderColor: '#008D49',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    padding: 12,
  },
  statusCopy: {
    flex: 1,
    gap: 4,
  },
  statusText: {
    color: '#557669',
    fontSize: 12,
    lineHeight: 17,
  },
  statusTitle: {
    color: '#008D49',
    fontSize: 14,
    fontWeight: '900',
  },
  subtitle: {
    color: '#557669',
    fontSize: 14,
    lineHeight: 20,
  },
  suggestions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  suggestionChip: {
    backgroundColor: '#E8F3EF',
    borderRadius: 8,
    minHeight: 36,
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  suggestionText: {
    color: '#008D49',
    fontSize: 13,
    fontWeight: '900',
  },
  summaryColumn: {
    flexShrink: 0,
    width: '100%',
  },
  summaryColumnWide: {
    width: 350,
  },
  summaryLabel: {
    color: '#557669',
    fontSize: 13,
    fontWeight: '800',
  },
  summaryPanel: {
    backgroundColor: '#FFFFFF',
    borderColor: '#008D49',
    borderRadius: 8,
    borderWidth: 1,
    gap: 12,
    padding: 12,
  },
  summaryRow: {
    alignItems: 'center',
    borderBottomColor: '#E8F3EF',
    borderBottomWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 10,
    paddingBottom: 10,
  },
  summaryRows: {
    gap: 10,
  },
  summaryValue: {
    color: '#12382C',
    flexShrink: 1,
    fontSize: 15,
    fontWeight: '900',
    textAlign: 'right',
  },
  tariffCard: {
    backgroundColor: '#FFFFFF',
    borderColor: 'rgba(18, 56, 44, 0.1)',
    borderRadius: 8,
    borderWidth: 1,
    elevation: 1,
    flex: 1,
    gap: 8,
    minWidth: 190,
    padding: 14,
    shadowColor: 'rgba(18, 56, 44, 0.12)',
    shadowOffset: { height: 3, width: 0 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
  },
  tariffCardActive: {
    backgroundColor: '#008D49',
    borderColor: '#008D49',
  },
  tariffEta: {
    color: '#557669',
    fontSize: 12,
    fontWeight: '800',
  },
  tariffEtaActive: {
    color: '#F4FAF6',
  },
  tariffGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  tariffMeta: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 10,
  },
  tariffPrice: {
    color: '#12382C',
    fontSize: 18,
    fontWeight: '900',
  },
  tariffPriceActive: {
    color: '#F4FAF6',
  },
  tariffSubtitle: {
    color: '#557669',
    fontSize: 12,
    lineHeight: 17,
  },
  tariffSubtitleActive: {
    color: '#F4FAF6',
  },
  tariffTitle: {
    color: '#12382C',
    flex: 1,
    fontSize: 16,
    fontWeight: '900',
  },
  tariffTitleActive: {
    color: '#F4FAF6',
  },
  tariffTop: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  timeline: {
    backgroundColor: '#FFFFFF',
    borderColor: '#008D49',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    padding: 10,
  },
  timelineDot: {
    alignItems: 'center',
    backgroundColor: '#E8F3EF',
    borderRadius: 8,
    height: 28,
    justifyContent: 'center',
    width: 28,
  },
  timelineDotActive: {
    backgroundColor: '#008D49',
  },
  timelineIndex: {
    color: '#557669',
    fontSize: 12,
    fontWeight: '900',
  },
  timelineIndexActive: {
    color: '#12382C',
  },
  timelineStep: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 7,
  },
  timelineText: {
    color: '#12382C',
    fontSize: 13,
    fontWeight: '800',
  },
  title: {
    color: '#12382C',
    fontSize: 24,
    fontWeight: '900',
    lineHeight: 30,
  },
  topBar: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    justifyContent: 'space-between',
  },
  userLine: {
    color: '#008D49',
    fontSize: 13,
    fontWeight: '900',
  },
});
