import { StyleSheet } from 'react-native';

import {
  kinetixColors,
  kinetixBorders,
  kinetixRadii,
  kinetixSpacing,
  kinetixTouchTargets,
  kinetixTypography,
} from '../theme/kinetixTokens';

export const styles = StyleSheet.create({
  actionRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  shell: {
    backgroundColor: '#F6F8F5',
    flex: 1,
  },
  scroll: {
    flex: 1,
  },
  accessPanel: {
    backgroundColor: '#FFFFFF',
    borderColor: 'rgba(18, 56, 44, 0.12)',
    borderRadius: 8,
    borderWidth: 1,
    gap: 5,
    padding: 12,
  },
  accessText: {
    color: '#557669',
    fontSize: 12,
    lineHeight: 17,
  },
  accessTitle: {
    color: '#12382C',
    fontSize: 13,
    fontWeight: '900',
  },
  appMeta: {
    color: '#557669',
    fontSize: 13,
    marginTop: 2,
  },
  liveText: {
    color: '#008D49',
    fontSize: 12,
    fontWeight: '900',
    marginTop: 2,
  },
  appName: {
    color: '#12382C',
    fontSize: 18,
    fontWeight: '900',
  },
  avatar: {
    alignItems: 'center',
    backgroundColor: '#008D49',
    borderRadius: 8,
    height: 42,
    justifyContent: 'center',
    width: 42,
  },
  avatarText: {
    color: '#12382C',
    fontSize: 18,
    fontWeight: '900',
  },
  availableCarsButton: {
    alignItems: 'center',
    backgroundColor: '#008D49',
    borderColor: '#008D49',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 14,
    minHeight: 88,
    padding: 12,
  },
  availableCarsCopy: {
    flex: 1,
    gap: 3,
    minWidth: 0,
  },
  availableCarsHint: {
    color: '#E8F3EF',
    fontSize: 13,
    fontWeight: '800',
    lineHeight: 18,
  },
  availableCarsIcon: {
    alignItems: 'center',
    backgroundColor: '#F4FAF6',
    borderRadius: 8,
    height: 46,
    justifyContent: 'center',
    width: 46,
  },
  availableCarsLabel: {
    color: '#E8F3EF',
    fontSize: 13,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  availableCarsValue: {
    color: '#FFFFFF',
    fontSize: 34,
    fontWeight: '900',
    lineHeight: 38,
  },
  callTaxiButton: {
    alignItems: 'center',
    backgroundColor: '#008D49',
    borderColor: '#008D49',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 14,
    minHeight: 112,
    padding: 14,
  },
  callTaxiCopy: {
    flex: 1,
    gap: 4,
    minWidth: 0,
  },
  callTaxiHint: {
    color: '#E8F3EF',
    fontSize: 13,
    fontWeight: '800',
    lineHeight: 18,
  },
  callTaxiIcon: {
    alignItems: 'center',
    backgroundColor: '#F4FAF6',
    borderRadius: 8,
    height: 52,
    justifyContent: 'center',
    width: 52,
  },
  callTaxiLabel: {
    color: '#E8F3EF',
    fontSize: 12,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  callTaxiTitle: {
    color: '#FFFFFF',
    fontSize: 28,
    fontWeight: '900',
    lineHeight: 32,
  },
  badge: {
    backgroundColor: '#E8F3EF',
    borderRadius: 6,
    color: '#C17A70',
    fontSize: 10,
    fontWeight: '900',
    overflow: 'hidden',
    paddingHorizontal: 6,
    paddingVertical: 3,
  },
  brandCopy: {
    flex: 1,
    minWidth: 0,
  },
  brandMark: {
    alignItems: 'center',
    backgroundColor: '#008D49',
    borderRadius: 8,
    height: 46,
    justifyContent: 'center',
    width: 46,
  },
  brandRow: {
    alignItems: 'center',
    flexDirection: 'row',
    flexShrink: 1,
    gap: 12,
    minWidth: 0,
  },
  accountHeroAvatar: {
    alignItems: 'center',
    backgroundColor: '#008D49',
    borderColor: 'rgba(255, 255, 255, 0.72)',
    borderRadius: 999,
    borderWidth: 2,
    height: 62,
    justifyContent: 'center',
    width: 62,
  },
  accountHeroAvatarText: {
    color: '#F4FAF6',
    fontSize: 22,
    fontWeight: '900',
  },
  accountHeroBadge: {
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(0, 141, 73, 0.1)',
    borderColor: 'rgba(0, 141, 73, 0.22)',
    borderRadius: 999,
    borderWidth: 1,
    color: '#008D49',
    fontSize: 12,
    fontWeight: '900',
    overflow: 'hidden',
    paddingHorizontal: 9,
    paddingVertical: 4,
  },
  accountHeroCard: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: 'rgba(0, 141, 73, 0.2)',
    borderRadius: 8,
    borderWidth: 1,
    elevation: 2,
    flexDirection: 'row',
    gap: 14,
    padding: 14,
    shadowColor: 'rgba(18, 56, 44, 0.18)',
    shadowOffset: { height: 3, width: 0 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
  },
  accountHeroCopy: {
    flex: 1,
    gap: 5,
    minWidth: 0,
  },
  accountHeroMeta: {
    color: '#557669',
    fontSize: 13,
    fontWeight: '800',
  },
  accountHeroName: {
    color: '#12382C',
    fontSize: 23,
    fontWeight: '900',
    lineHeight: 28,
  },
  accountDangerButton: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#C17A70',
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    justifyContent: 'center',
    minHeight: 44,
    minWidth: 132,
    paddingHorizontal: 12,
  },
  accountDangerButtonText: {
    color: '#A55349',
    fontSize: 13,
    fontWeight: '900',
    textAlign: 'center',
  },
  accountProfileCard: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: 'rgba(11, 47, 37, 0.10)',
    borderRadius: 18,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 14,
    padding: 16,
  },
  accountProfileAvatar: {
    alignItems: 'center',
    backgroundColor: '#0B6B4A',
    borderRadius: 16,
    height: 54,
    justifyContent: 'center',
    width: 54,
  },
  accountProfileAvatarText: {
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: '800',
  },
  accountProfileName: {
    color: '#12382C',
    fontSize: 18,
    fontWeight: '800',
    letterSpacing: -0.3,
  },
  accountProfileMeta: {
    color: '#6E8579',
    fontSize: 13,
    marginTop: 2,
  },
  accountDangerRow: {
    alignItems: 'center',
    borderColor: 'rgba(255, 59, 48, 0.25)',
    borderRadius: 14,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 13,
    paddingHorizontal: 15,
    paddingVertical: 13,
  },
  accountDangerIcon: {
    alignItems: 'center',
    backgroundColor: 'rgba(255, 59, 48, 0.08)',
    borderColor: 'rgba(255, 59, 48, 0.20)',
    borderRadius: 12,
    borderWidth: 1,
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  accountDangerName: {
    color: '#D8352B',
    fontSize: 15,
    fontWeight: '700',
  },
  accountPanel: {
    backgroundColor: '#FFFFFF',
    borderColor: 'rgba(18, 56, 44, 0.12)',
    borderRadius: 8,
    borderWidth: 1,
    elevation: 1,
    gap: 12,
    padding: 14,
    shadowColor: 'rgba(18, 56, 44, 0.14)',
    shadowOffset: { height: 3, width: 0 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
  },
  accountPanelTitle: {
    color: '#12382C',
    fontSize: 18,
    fontWeight: '900',
  },
  aboutBrandCard: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: 'rgba(11, 47, 37, 0.10)',
    borderRadius: 20,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 14,
    padding: 16,
    shadowColor: '#0B2F25',
    shadowOffset: { height: 10, width: 0 },
    shadowOpacity: 0.05,
    shadowRadius: 20,
  },
  aboutBrandTile: {
    alignItems: 'center',
    backgroundColor: '#0A1411',
    borderRadius: 16,
    height: 52,
    justifyContent: 'center',
    width: 52,
  },
  aboutBrandMark: {
    color: '#B7F46A',
    fontSize: 26,
    fontWeight: '800',
    letterSpacing: -1,
  },
  aboutBrandCopy: {
    flex: 1,
    minWidth: 0,
  },
  aboutBrandName: {
    color: '#12382C',
    fontSize: 20,
    fontWeight: '800',
    letterSpacing: -0.4,
  },
  aboutBrandSub: {
    color: '#6E8579',
    fontSize: 13,
    marginTop: 2,
  },
  aboutVersionPill: {
    backgroundColor: 'rgba(0, 141, 73, 0.10)',
    borderRadius: 999,
    paddingHorizontal: 11,
    paddingVertical: 6,
  },
  aboutVersionText: {
    color: '#008D49',
    fontSize: 12,
    fontWeight: '800',
  },
  aboutSection: {
    backgroundColor: '#FFFFFF',
    borderColor: 'rgba(11, 47, 37, 0.10)',
    borderRadius: 20,
    borderWidth: 1,
    gap: 12,
    padding: 18,
    shadowColor: '#0B2F25',
    shadowOffset: { height: 10, width: 0 },
    shadowOpacity: 0.05,
    shadowRadius: 20,
  },
  aboutSectionTitle: {
    color: '#12382C',
    fontSize: 16,
    fontWeight: '800',
    letterSpacing: -0.2,
  },
  aboutRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 13,
  },
  aboutRowIcon: {
    alignItems: 'center',
    backgroundColor: 'rgba(0, 141, 73, 0.10)',
    borderRadius: 13,
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  aboutRowCopy: {
    flex: 1,
    minWidth: 0,
  },
  aboutRowTitle: {
    color: '#12382C',
    fontSize: 15,
    fontWeight: '800',
  },
  aboutRowText: {
    color: '#6E8579',
    fontSize: 13,
    marginTop: 1,
  },
  aboutHonestCard: {
    alignItems: 'center',
    backgroundColor: '#0A1411',
    borderRadius: 20,
    flexDirection: 'row',
    gap: 13,
    overflow: 'hidden',
    padding: 18,
    position: 'relative',
  },
  aboutHonestGlow: {
    backgroundColor: 'rgba(92, 230, 160, 0.10)',
    borderRadius: 80,
    height: 160,
    position: 'absolute',
    right: -50,
    top: -40,
    width: 160,
  },
  aboutHonestIcon: {
    alignItems: 'center',
    backgroundColor: 'rgba(183, 244, 106, 0.12)',
    borderColor: 'rgba(183, 244, 106, 0.22)',
    borderRadius: 13,
    borderWidth: 1,
    height: 44,
    justifyContent: 'center',
    width: 44,
    zIndex: 1,
  },
  aboutHonestText: {
    color: '#D6E9DE',
    flex: 1,
    fontSize: 13,
    fontWeight: '600',
    lineHeight: 19,
    minWidth: 0,
    zIndex: 1,
  },
  aboutMeta: {
    color: '#8AA398',
    fontSize: 12,
    fontWeight: '600',
    textAlign: 'center',
  },
  driverHome: {
    gap: 14,
  },
  driverHero: {
    backgroundColor: '#0A1411',
    borderBottomLeftRadius: 28,
    borderBottomRightRadius: 28,
    marginHorizontal: -14,
    marginTop: -14,
    overflow: 'hidden',
    paddingBottom: 22,
    paddingHorizontal: 20,
    paddingTop: 24,
    position: 'relative',
  },
  driverHeroGlow: {
    backgroundColor: 'rgba(92, 230, 160, 0.10)',
    borderRadius: 90,
    height: 180,
    position: 'absolute',
    right: -40,
    top: -30,
    width: 180,
  },
  driverHeroTop: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    position: 'relative',
    zIndex: 1,
  },
  driverHeroEyebrow: {
    color: '#93BAA8',
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  driverHeroPill: {
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderColor: 'rgba(255, 255, 255, 0.12)',
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 7,
    paddingHorizontal: 11,
    paddingVertical: 6,
  },
  driverHeroPillOn: {
    backgroundColor: 'rgba(92, 230, 160, 0.12)',
    borderColor: 'rgba(92, 230, 160, 0.30)',
  },
  driverHeroDot: {
    backgroundColor: '#6E8579',
    borderRadius: 4,
    height: 8,
    width: 8,
  },
  driverHeroDotOn: {
    backgroundColor: '#B7F46A',
  },
  driverHeroPillText: {
    color: '#93BAA8',
    fontSize: 12,
    fontWeight: '800',
  },
  driverHeroPillTextOn: {
    color: '#5CE6A0',
  },
  driverHeroTitle: {
    color: '#F2FBF6',
    fontSize: 25,
    fontWeight: '800',
    letterSpacing: -0.5,
    marginTop: 16,
    position: 'relative',
    zIndex: 1,
  },
  driverHeroSub: {
    color: '#93BAA8',
    fontSize: 13,
    lineHeight: 18,
    marginTop: 4,
    position: 'relative',
    zIndex: 1,
  },
  driverHeroCta: {
    alignItems: 'center',
    backgroundColor: '#B7F46A',
    borderRadius: 16,
    flexDirection: 'row',
    gap: 9,
    justifyContent: 'center',
    marginTop: 18,
    minHeight: 54,
    paddingHorizontal: 16,
    position: 'relative',
    zIndex: 1,
  },
  driverHeroCtaStop: {
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderColor: 'rgba(255, 255, 255, 0.16)',
    borderWidth: 1,
  },
  driverHeroCtaDisabled: {
    opacity: 0.5,
  },
  driverHeroCtaText: {
    color: '#0A1411',
    fontSize: 16,
    fontWeight: '800',
  },
  driverHeroCtaTextStop: {
    color: '#F2FBF6',
  },
  driverStatsRow: {
    flexDirection: 'row',
    gap: 10,
  },
  driverStatCard: {
    backgroundColor: '#FFFFFF',
    borderColor: 'rgba(11, 47, 37, 0.10)',
    borderRadius: 18,
    borderWidth: 1,
    flex: 1,
    gap: 8,
    minWidth: 0,
    padding: 14,
    shadowColor: '#0B2F25',
    shadowOffset: { height: 10, width: 0 },
    shadowOpacity: 0.05,
    shadowRadius: 20,
  },
  driverStatIcon: {
    alignItems: 'center',
    backgroundColor: 'rgba(0, 141, 73, 0.10)',
    borderRadius: 11,
    height: 38,
    justifyContent: 'center',
    width: 38,
  },
  driverStatValue: {
    color: '#12382C',
    fontSize: 18,
    fontWeight: '800',
    letterSpacing: -0.4,
  },
  driverStatLabel: {
    color: '#6E8579',
    fontSize: 12,
    fontWeight: '700',
  },
  driverAccessCard: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: 'rgba(11, 47, 37, 0.10)',
    borderRadius: 18,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 13,
    padding: 15,
    shadowColor: '#0B2F25',
    shadowOffset: { height: 10, width: 0 },
    shadowOpacity: 0.05,
    shadowRadius: 20,
  },
  driverAccessCardWarn: {
    backgroundColor: '#FFFCF3',
    borderColor: 'rgba(231, 180, 22, 0.35)',
  },
  driverAccessCardIcon: {
    alignItems: 'center',
    backgroundColor: 'rgba(0, 141, 73, 0.10)',
    borderRadius: 12,
    height: 42,
    justifyContent: 'center',
    width: 42,
  },
  driverAccessCardIconWarn: {
    backgroundColor: 'rgba(231, 180, 22, 0.14)',
  },
  driverAccessCardCopy: {
    flex: 1,
    minWidth: 0,
  },
  driverAccessCardTitle: {
    color: '#12382C',
    fontSize: 15,
    fontWeight: '800',
  },
  driverAccessCardText: {
    color: '#6E8579',
    fontSize: 13,
    lineHeight: 18,
    marginTop: 2,
  },
  driverActionRow: {
    flexDirection: 'row',
    gap: 10,
  },
  driverActionBtn: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: 'rgba(11, 47, 37, 0.10)',
    borderRadius: 14,
    borderWidth: 1,
    flex: 1,
    flexDirection: 'row',
    gap: 7,
    justifyContent: 'center',
    minHeight: 48,
    paddingHorizontal: 8,
    shadowColor: '#0B2F25',
    shadowOffset: { height: 6, width: 0 },
    shadowOpacity: 0.04,
    shadowRadius: 12,
  },
  driverActionBtnActive: {
    backgroundColor: '#B7F46A',
    borderColor: '#B7F46A',
  },
  driverActionText: {
    color: '#12382C',
    fontSize: 14,
    fontWeight: '800',
  },
  driverActionTextActive: {
    color: '#0A1411',
  },
  accountProfileActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  accountProfileLabel: {
    color: '#557669',
    fontSize: 12,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  accountProfileRow: {
    backgroundColor: '#F7FBF8',
    borderColor: 'rgba(0, 141, 73, 0.14)',
    borderRadius: 8,
    borderWidth: 1,
    gap: 5,
    padding: 12,
  },
  accountProfileValue: {
    color: '#12382C',
    fontSize: 15,
    fontWeight: '900',
  },
  accountRoundButton: {
    alignItems: 'center',
    flex: 1,
    gap: 8,
    minWidth: 92,
  },
  accountRoundIcon: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: 'rgba(18, 56, 44, 0.12)',
    borderRadius: 999,
    borderWidth: 1,
    elevation: 1,
    height: 68,
    justifyContent: 'center',
    shadowColor: 'rgba(18, 56, 44, 0.14)',
    shadowOffset: { height: 3, width: 0 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    width: 68,
  },
  accountRoundIconActive: {
    backgroundColor: '#008D49',
    borderColor: '#008D49',
    shadowColor: 'rgba(0, 111, 58, 0.22)',
    shadowOpacity: 0.16,
  },
  accountRoundRow: {
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'space-between',
  },
  accountRoundText: {
    color: '#12382C',
    fontSize: 13,
    fontWeight: '900',
    textAlign: 'center',
  },
  accountRoundTextActive: {
    color: '#008D49',
  },
  accountSecondaryButton: {
    alignItems: 'center',
    backgroundColor: '#F1F8F3',
    borderColor: 'rgba(0, 141, 73, 0.28)',
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    justifyContent: 'center',
    minHeight: 44,
    minWidth: 132,
    paddingHorizontal: 12,
  },
  accountSecondaryButtonText: {
    color: '#008D49',
    fontSize: 13,
    fontWeight: '900',
    textAlign: 'center',
  },
  clientActiveOrderCard: {
    backgroundColor: '#FFFFFF',
    borderColor: '#008D49',
    borderRadius: 8,
    borderWidth: 1,
    gap: 5,
    padding: 12,
  },
  clientActiveOrderLabel: {
    color: '#008D49',
    fontSize: 12,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  clientActiveOrderText: {
    color: '#557669',
    fontSize: 13,
    lineHeight: 18,
  },
  clientActiveOrderTitle: {
    color: '#12382C',
    fontSize: 16,
    fontWeight: '900',
  },
  clientEmptyOrderCard: {
    backgroundColor: '#F7FBF8',
    borderColor: 'rgba(18, 56, 44, 0.1)',
    borderRadius: 8,
    borderWidth: 1,
    gap: 6,
    padding: 14,
  },
  clientFocusPage: {
    gap: 14,
  },
  clientHome: {
    gap: 16,
  },
  clientHero: {
    backgroundColor: '#0A1411',
    borderBottomLeftRadius: 28,
    borderBottomRightRadius: 28,
    marginHorizontal: -14,
    marginTop: -14,
    overflow: 'hidden',
    paddingBottom: 22,
    paddingHorizontal: 20,
    paddingTop: 24,
    position: 'relative',
  },
  clientHeroGlow: {
    backgroundColor: 'rgba(92, 230, 160, 0.10)',
    borderRadius: 90,
    height: 180,
    position: 'absolute',
    right: -34,
    top: -34,
    width: 180,
  },
  clientHeroRow: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  clientHeroCopy: {
    flex: 1,
    paddingRight: 12,
  },
  clientHeroGreeting: {
    color: '#F2FBF6',
    fontSize: 22,
    fontWeight: '800',
    letterSpacing: -0.5,
  },
  clientHeroSub: {
    color: '#93BAA8',
    fontSize: 13.5,
    marginTop: 5,
  },
  clientHeroMenu: {
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.07)',
    borderColor: 'rgba(92, 230, 160, 0.22)',
    borderRadius: 14,
    borderWidth: 1,
    height: 46,
    justifyContent: 'center',
    width: 46,
  },
  clientHomeBody: {
    gap: 15,
  },
  clientMapCard: {
    backgroundColor: '#DDECE3',
    borderColor: 'rgba(11, 47, 37, 0.10)',
    borderRadius: 20,
    borderWidth: 1,
    height: 212,
    overflow: 'hidden',
    position: 'relative',
  },
  clientMapChip: {
    alignItems: 'center',
    backgroundColor: 'rgba(10, 20, 17, 0.82)',
    borderRadius: 999,
    flexDirection: 'row',
    gap: 7,
    left: 12,
    paddingHorizontal: 12,
    paddingVertical: 6,
    position: 'absolute',
    top: 12,
  },
  clientMapChipDot: {
    backgroundColor: '#B7F46A',
    borderRadius: 4,
    height: 7,
    width: 7,
  },
  clientMapChipText: {
    color: '#EAF6EF',
    fontSize: 12,
    fontWeight: '600',
  },
  clientMapWhere: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    bottom: 12,
    elevation: 4,
    flexDirection: 'row',
    gap: 11,
    left: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    position: 'absolute',
    right: 12,
    shadowColor: '#002816',
    shadowOffset: { height: 6, width: 0 },
    shadowOpacity: 0.16,
    shadowRadius: 14,
  },
  clientMapSearchIcon: {
    alignItems: 'center',
    backgroundColor: '#0A1411',
    borderRadius: 11,
    height: 34,
    justifyContent: 'center',
    width: 34,
  },
  clientMapWhereText: {
    color: '#12382C',
    flex: 1,
    fontSize: 16,
    fontWeight: '700',
  },
  clientActionPrimary: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: 'rgba(11, 47, 37, 0.10)',
    borderRadius: 20,
    borderWidth: 1,
    elevation: 2,
    flexDirection: 'row',
    gap: 15,
    padding: 17,
    shadowColor: '#005A30',
    shadowOffset: { height: 4, width: 0 },
    shadowOpacity: 0.07,
    shadowRadius: 12,
  },
  clientActionSecondary: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: 'rgba(11, 47, 37, 0.10)',
    borderRadius: 20,
    borderWidth: 1,
    elevation: 2,
    flexDirection: 'row',
    gap: 15,
    paddingHorizontal: 18,
    paddingVertical: 15,
    shadowColor: '#005A30',
    shadowOffset: { height: 4, width: 0 },
    shadowOpacity: 0.07,
    shadowRadius: 12,
  },
  clientActionIconPrimary: {
    alignItems: 'center',
    backgroundColor: '#0B6B4A',
    borderRadius: 15,
    height: 50,
    justifyContent: 'center',
    width: 50,
  },
  clientActionIconSecondary: {
    alignItems: 'center',
    backgroundColor: '#F7FBF8',
    borderColor: 'rgba(0, 141, 73, 0.20)',
    borderRadius: 15,
    borderWidth: 1,
    height: 50,
    justifyContent: 'center',
    width: 50,
  },
  clientActionCopy: {
    flex: 1,
    minWidth: 0,
  },
  clientActionTitle: {
    color: '#12382C',
    fontSize: 19,
    fontWeight: '800',
    letterSpacing: -0.35,
  },
  clientActionTitleSm: {
    color: '#12382C',
    fontSize: 17,
    fontWeight: '800',
    letterSpacing: -0.3,
  },
  clientActionSub: {
    color: '#6E8579',
    fontSize: 13,
    marginTop: 2,
  },
  clientFavSection: {
    gap: 8,
    marginTop: 2,
  },
  clientFavTitle: {
    color: '#12382C',
    fontSize: 14,
    fontWeight: '700',
    marginBottom: 2,
    paddingHorizontal: 2,
  },
  clientFavRow: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: 'rgba(11, 47, 37, 0.10)',
    borderRadius: 14,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 13,
    paddingHorizontal: 15,
    paddingVertical: 13,
  },
  clientFavIcon: {
    alignItems: 'center',
    backgroundColor: '#F7FBF8',
    borderColor: 'rgba(0, 141, 73, 0.16)',
    borderRadius: 12,
    borderWidth: 1,
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  clientFavName: {
    color: '#12382C',
    fontSize: 15,
    fontWeight: '700',
  },
  clientFavAddr: {
    color: '#6E8579',
    fontSize: 13,
    marginTop: 1,
  },
  clientFavAdd: {
    alignItems: 'center',
    borderColor: 'rgba(0, 141, 73, 0.30)',
    borderRadius: 14,
    borderStyle: 'dashed',
    borderWidth: 1,
    flexDirection: 'row',
    gap: 9,
    justifyContent: 'center',
    paddingVertical: 14,
  },
  clientFavAddText: {
    color: '#008D49',
    fontSize: 14,
    fontWeight: '700',
  },
  activeOrderCard: {
    alignItems: 'center',
    backgroundColor: '#5CE6A0',
    borderRadius: 16,
    flexDirection: 'row',
    gap: 12,
    minHeight: 64,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  activeOrderIcon: {
    alignItems: 'center',
    backgroundColor: 'rgba(6, 20, 13, 0.12)',
    borderRadius: 12,
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  activeOrderCopy: {
    flex: 1,
    gap: 2,
    minWidth: 0,
  },
  activeOrderLabel: {
    color: 'rgba(6, 20, 13, 0.72)',
    fontSize: 12,
    fontWeight: '800',
  },
  activeOrderRoute: {
    color: '#06140D',
    fontSize: 15,
    fontWeight: '900',
  },
  activeOrderArrow: {
    color: '#06140D',
    fontSize: 22,
    fontWeight: '900',
  },
  clientHeaderActions: {
    alignItems: 'center',
    flexDirection: 'row',
    flexShrink: 0,
    gap: kinetixSpacing.xs,
  },
  clientHeaderAvatar: {
    alignItems: 'center',
    backgroundColor: kinetixColors.amber,
    borderColor: kinetixColors.glassStrong,
    borderRadius: kinetixRadii.mapPin,
    borderWidth: kinetixBorders.active,
    height: kinetixTouchTargets.icon - kinetixSpacing.xxs,
    justifyContent: 'center',
    shadowColor: kinetixColors.shadow,
    shadowOffset: { height: 8, width: 0 },
    shadowOpacity: 0.16,
    shadowRadius: 14,
    width: kinetixTouchTargets.icon - kinetixSpacing.xxs,
  },
  clientHeaderAvatarText: {
    color: kinetixColors.graphite,
    fontSize: kinetixTypography.sizes.meta,
    fontWeight: kinetixTypography.weights.bold,
  },
  clientHeaderCopy: {
    flex: 1,
    gap: 5,
    minWidth: 0,
  },
  clientHeaderGreeting: {
    color: kinetixColors.textMuted,
    fontSize: kinetixTypography.sizes.caption,
    fontWeight: kinetixTypography.weights.semibold,
    lineHeight: kinetixTypography.lineHeights.caption,
  },
  clientHeaderIconButton: {
    alignItems: 'center',
    backgroundColor: 'transparent',
    borderColor: 'transparent',
    borderRadius: kinetixRadii.mapPin,
    borderWidth: 0,
    elevation: 0,
    height: kinetixTouchTargets.icon,
    justifyContent: 'center',
    width: kinetixTouchTargets.icon,
  },
  clientHeaderMenuButton: {
    alignItems: 'center',
    backgroundColor: 'rgba(0, 141, 73, 0.12)',
    borderColor: 'rgba(0, 141, 73, 0.24)',
    borderRadius: kinetixRadii.mapPin,
    borderWidth: 1,
    height: kinetixTouchTargets.icon,
    justifyContent: 'center',
    width: kinetixTouchTargets.icon,
  },
  clientHeaderLeft: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    gap: kinetixSpacing.sm,
    minWidth: 0,
  },
  clientHeaderStatusPill: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: kinetixColors.amberSoft,
    borderRadius: kinetixRadii.mapPin,
    flexDirection: 'row',
    gap: 5,
    minHeight: kinetixTouchTargets.icon - kinetixSpacing.lg,
    paddingHorizontal: 10,
  },
  clientHeaderStatusText: {
    color: kinetixColors.amber,
    fontSize: kinetixTypography.sizes.caption,
    fontWeight: kinetixTypography.weights.bold,
  },
  clientTopBar: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: kinetixSpacing.sm,
    justifyContent: 'space-between',
    paddingBottom: 4,
    paddingTop: 2,
  },
  clientDeliveryActionButton: {
    backgroundColor: '#F1F8F3',
    borderColor: 'rgba(0, 141, 73, 0.32)',
  },
  clientDeliveryActionTop: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
  },
  clientDeliveryBadge: {
    backgroundColor: '#008D49',
    borderRadius: 999,
    color: '#F4FAF6',
    fontSize: 10,
    fontWeight: '900',
    overflow: 'hidden',
    paddingHorizontal: 7,
    paddingVertical: 3,
  },
  clientHistoryActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  clientHistoryButton: {
    alignItems: 'center',
    backgroundColor: '#008D49',
    borderRadius: 8,
    elevation: 2,
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'center',
    minHeight: 52,
    paddingHorizontal: 14,
    shadowColor: 'rgba(18, 56, 44, 0.16)',
    shadowOffset: { height: 7, width: 0 },
    shadowOpacity: 0.12,
    shadowRadius: 14,
  },
  clientHistoryButtonText: {
    color: '#F4FAF6',
    fontSize: 15,
    fontWeight: '900',
  },
  clientHistoryMiniButton: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: 'rgba(0, 141, 73, 0.24)',
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 5,
    minHeight: 34,
    paddingHorizontal: 10,
  },
  clientHistoryMiniButtonText: {
    color: '#008D49',
    fontSize: 12,
    fontWeight: '900',
  },
  clientHistoryChip: {
    backgroundColor: '#F1F8F3',
    borderColor: 'rgba(18, 56, 44, 0.1)',
    borderRadius: 999,
    borderWidth: 1,
    minHeight: 34,
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
  clientHistoryChipText: {
    color: '#008D49',
    fontSize: 12,
    fontWeight: '900',
  },
  clientTripCard: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: 'rgba(18, 56, 44, 0.1)',
    borderRadius: 8,
    borderWidth: 1,
    elevation: 1,
    flexDirection: 'row',
    gap: 10,
    minHeight: 74,
    padding: 10,
    shadowColor: 'rgba(18, 56, 44, 0.14)',
    shadowOffset: { height: 3, width: 0 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
  },
  clientTripCardActive: {
    borderColor: '#008D49',
  },
  clientTripCopy: {
    flex: 1,
    gap: 4,
    minWidth: 0,
  },
  clientTripIcon: {
    alignItems: 'center',
    backgroundColor: '#F1F8F3',
    borderColor: 'rgba(0, 141, 73, 0.18)',
    borderRadius: 8,
    borderWidth: 1,
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  clientTripIconActive: {
    backgroundColor: '#008D49',
    borderColor: '#008D49',
  },
  clientTripMeta: {
    color: '#557669',
    fontSize: 12,
    fontWeight: '800',
  },
  clientTripPrice: {
    color: '#008D49',
    flexShrink: 0,
    fontSize: 14,
    fontWeight: '900',
  },
  clientTripStatus: {
    backgroundColor: '#F1F8F3',
    borderRadius: 999,
    color: '#008D49',
    flexShrink: 0,
    fontSize: 11,
    fontWeight: '900',
    maxWidth: 96,
    overflow: 'hidden',
    paddingHorizontal: 8,
    paddingVertical: 5,
  },
  clientTripStatusActive: {
    backgroundColor: '#008D49',
    color: '#F4FAF6',
  },
  clientTripsList: {
    gap: 8,
  },
  clientTripTitle: {
    color: '#12382C',
    flex: 1,
    fontSize: 15,
    fontWeight: '900',
    minWidth: 0,
  },
  clientTripTop: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  clientHomeActionButton: {
    backgroundColor: '#FFFFFF',
    borderColor: 'rgba(0, 141, 73, 0.18)',
    borderRadius: 8,
    borderWidth: 1,
    elevation: 2,
    flex: 1,
    gap: 6,
    minHeight: 104,
    minWidth: 142,
    padding: 14,
    shadowColor: 'rgba(18, 56, 44, 0.18)',
    shadowOffset: { height: 3, width: 0 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
  },
  clientHomeActionRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  clientHomeActionText: {
    color: '#557669',
    fontSize: 12,
    lineHeight: 17,
  },
  clientHomeActionTitle: {
    color: '#12382C',
    fontSize: 17,
    fontWeight: '900',
  },
  clientLastOrderBox: {
    backgroundColor: '#FFFFFF',
    borderColor: 'rgba(18, 56, 44, 0.1)',
    borderRadius: 8,
    borderWidth: 1,
    gap: 5,
    padding: 12,
  },
  clientLastOrderStatus: {
    color: '#008D49',
    fontSize: 12,
    fontWeight: '900',
  },
  clientLastOrderText: {
    color: '#557669',
    fontSize: 13,
    lineHeight: 18,
  },
  clientLastOrderTitle: {
    color: '#12382C',
    fontSize: 15,
    fontWeight: '900',
  },
  clientMain: {
    width: '100%',
  },
  clientMainOrderIcon: {
    alignItems: 'center',
    backgroundColor: 'rgba(244, 250, 246, 0.16)',
    borderRadius: 8,
    height: 58,
    justifyContent: 'center',
    width: 58,
  },
  clientServiceRow: {
    flexDirection: 'row',
    gap: 12,
  },
  clientServiceText: {
    color: '#DDF1E7',
    fontSize: 13,
    fontWeight: '700',
  },
  clientServiceTile: {
    alignItems: 'flex-start',
    backgroundColor: '#008D49',
    borderColor: '#008D49',
    borderRadius: 8,
    borderWidth: 1,
    elevation: 2,
    flex: 1,
    gap: 10,
    minHeight: 132,
    padding: 16,
    shadowColor: 'rgba(0, 111, 58, 0.28)',
    shadowOffset: { height: 3, width: 0 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
  },
  clientServiceTitle: {
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: '900',
    lineHeight: 24,
  },
  clientTrustChip: {
    alignItems: 'flex-start',
    backgroundColor: kinetixColors.surface,
    borderColor: kinetixColors.line,
    borderRadius: kinetixRadii.card,
    borderWidth: kinetixBorders.hairline,
    flexBasis: '48%',
    flexGrow: 1,
    flexDirection: 'row',
    gap: kinetixSpacing.xs,
    minHeight: 76,
    minWidth: 150,
    paddingHorizontal: kinetixSpacing.sm,
    paddingVertical: kinetixSpacing.sm,
  },
  clientTrustCopy: {
    flex: 1,
    gap: 3,
    minWidth: 0,
  },
  clientTrustDot: {
    backgroundColor: kinetixColors.lime,
    borderColor: kinetixColors.amber,
    borderRadius: 999,
    borderWidth: kinetixBorders.hairline,
    height: 10,
    width: 10,
  },
  clientTrustIcon: {
    alignItems: 'center',
    backgroundColor: kinetixColors.amberSoft,
    borderRadius: kinetixRadii.mapPin,
    height: 32,
    justifyContent: 'center',
    width: 32,
  },
  clientTrustDotLive: {
    backgroundColor: kinetixColors.amber,
    borderRadius: kinetixRadii.mapPin,
    height: 7,
    width: 7,
  },
  clientTrustRail: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: kinetixSpacing.xs,
  },
  clientTrustText: {
    color: kinetixColors.textPrimary,
    flex: 1,
    fontSize: kinetixTypography.sizes.meta,
    fontWeight: kinetixTypography.weights.bold,
    minWidth: 0,
  },
  clientTrustTitle: {
    color: kinetixColors.textMuted,
    fontSize: kinetixTypography.sizes.caption,
    fontWeight: kinetixTypography.weights.medium,
  },
  clientTrustValueRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: kinetixSpacing.xxs,
    minWidth: 0,
  },
  clientMapCanvas: {
    backgroundColor: '#DDECE3',
    borderRadius: 8,
    height: 172,
    overflow: 'hidden',
    position: 'relative',
  },
  clientMapCopy: {
    gap: kinetixSpacing.xxs,
  },
  clientMapMeta: {
    color: '#008D49',
    fontSize: 12,
    fontWeight: '900',
  },
  clientMapGlow: {
    backgroundColor: 'rgba(183, 244, 106, 0.34)',
    borderRadius: 999,
    height: 142,
    position: 'absolute',
    right: -34,
    top: -42,
    width: 142,
  },
  clientMapPanel: {
    backgroundColor: '#FFFFFF',
    borderColor: 'rgba(0, 141, 73, 0.22)',
    borderRadius: 8,
    borderWidth: 1,
    elevation: 2,
    gap: 10,
    padding: 12,
    shadowColor: 'rgba(18, 56, 44, 0.18)',
    shadowOffset: { height: 3, width: 0 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
  },
  clientMapDistrictOne: {
    backgroundColor: 'rgba(255,255,255,0.42)',
    borderColor: 'rgba(0, 141, 73, 0.08)',
    borderRadius: 8,
    borderWidth: 1,
    height: 64,
    left: 18,
    position: 'absolute',
    top: 18,
    width: 96,
  },
  clientMapDistrictTwo: {
    backgroundColor: 'rgba(255,255,255,0.36)',
    borderColor: 'rgba(0, 141, 73, 0.08)',
    borderRadius: 8,
    borderWidth: 1,
    bottom: 16,
    height: 58,
    position: 'absolute',
    right: 24,
    width: 108,
  },
  clientMapRoad: {
    backgroundColor: 'rgba(255,255,255,0.72)',
    height: 22,
    left: -18,
    position: 'absolute',
    right: -18,
    top: 62,
  },
  clientMapRoadOne: {
    transform: [{ rotate: '-18deg' }],
  },
  clientMapRoadTwo: {
    top: 88,
    transform: [{ rotate: '22deg' }],
  },
  clientMapRoadThree: {
    height: 18,
    top: 28,
    transform: [{ rotate: '41deg' }],
  },
  clientMapRouteLine: {
    backgroundColor: '#00A855',
    borderRadius: 99,
    elevation: 2,
    height: 5,
    left: 34,
    position: 'absolute',
    right: 42,
    shadowColor: 'rgba(0, 168, 85, 0.42)',
    shadowOffset: { height: 0, width: 0 },
    shadowOpacity: 0.35,
    shadowRadius: 8,
    top: 84,
    transform: [{ rotate: '9deg' }],
  },
  clientMapStatusPill: {
    backgroundColor: kinetixColors.amber,
    borderColor: kinetixColors.glassStrong,
    borderRadius: kinetixRadii.mapPin,
    borderWidth: kinetixBorders.hairline,
    paddingHorizontal: kinetixSpacing.sm,
    paddingVertical: kinetixSpacing.xxs,
    position: 'absolute',
    right: kinetixSpacing.sm,
    top: kinetixSpacing.sm,
  },
  clientMapStatusText: {
    color: kinetixColors.surface,
    fontSize: kinetixTypography.sizes.caption - 1,
    fontWeight: kinetixTypography.weights.bold,
  },
  clientMapText: {
    color: kinetixColors.textSecondary,
    fontSize: kinetixTypography.sizes.meta,
    lineHeight: kinetixTypography.lineHeights.meta,
  },
  clientMapTitle: {
    color: kinetixColors.textPrimary,
    fontSize: kinetixTypography.sizes.body,
    fontWeight: kinetixTypography.weights.bold,
  },
  clientCarMarker: {
    alignItems: 'center',
    backgroundColor: '#008D49',
    borderColor: '#FFFFFF',
    borderRadius: 8,
    borderWidth: 2,
    height: 42,
    justifyContent: 'center',
    position: 'absolute',
    right: 36,
    top: 58,
    width: 42,
  },
  clientPassengerDot: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#008D49',
    borderRadius: 999,
    borderWidth: 2,
    height: 24,
    justifyContent: 'center',
    left: 32,
    position: 'absolute',
    top: 81,
    width: 24,
  },
  clientPassengerPulse: {
    backgroundColor: '#008D49',
    borderRadius: 999,
    height: 10,
    width: 10,
  },
  clientPassengerPulseOuter: {
    backgroundColor: 'rgba(0, 168, 85, 0.26)',
    borderRadius: 999,
    height: 22,
    position: 'absolute',
    width: 22,
  },
  clientSectionHeader: {
    gap: 3,
    paddingHorizontal: 4,
    paddingTop: 4,
  },
  clientPageHero: {
    backgroundColor: '#0A1411',
    borderBottomLeftRadius: 26,
    borderBottomRightRadius: 26,
    marginHorizontal: -14,
    marginTop: -14,
    overflow: 'hidden',
    paddingBottom: 18,
    paddingHorizontal: 18,
    paddingTop: 22,
    position: 'relative',
  },
  clientPageHeroRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 13,
    position: 'relative',
    zIndex: 1,
  },
  clientPageHeroIcon: {
    alignItems: 'center',
    backgroundColor: 'rgba(92, 230, 160, 0.12)',
    borderColor: 'rgba(92, 230, 160, 0.22)',
    borderRadius: 14,
    borderWidth: 1,
    height: 46,
    justifyContent: 'center',
    width: 46,
  },
  clientPageHeroCopy: {
    flex: 1,
    minWidth: 0,
  },
  clientPageHeroTitle: {
    color: '#F2FBF6',
    fontSize: 22,
    fontWeight: '800',
    letterSpacing: -0.5,
  },
  clientPageHeroSub: {
    color: '#93BAA8',
    fontSize: 13,
    marginTop: 3,
  },
  clientSectionText: {
    color: '#6E8579',
    fontSize: 13,
    lineHeight: 18,
  },
  clientSectionTitle: {
    color: '#12382C',
    fontSize: 24,
    fontWeight: '800',
    letterSpacing: -0.5,
  },
  clientSettingCopy: {
    flex: 1,
    gap: 3,
    minWidth: 0,
  },
  clientSettingKnob: {
    backgroundColor: '#FFFFFF',
    borderRadius: 999,
    height: 22,
    width: 22,
  },
  clientSettingKnobOn: {
    transform: [{ translateX: 22 }],
  },
  clientSettingRow: {
    alignItems: 'center',
    backgroundColor: '#F7FBF8',
    borderColor: 'rgba(18, 56, 44, 0.1)',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    minHeight: 70,
    padding: 10,
  },
  clientSettingSwitch: {
    alignItems: 'flex-start',
    backgroundColor: '#A9BBB3',
    borderRadius: 999,
    height: 28,
    justifyContent: 'center',
    padding: 3,
    width: 52,
  },
  clientSettingSwitchOn: {
    backgroundColor: '#008D49',
  },
  clientSettingText: {
    color: '#557669',
    fontSize: 12,
    lineHeight: 17,
  },
  clientSettingTitle: {
    color: '#12382C',
    fontSize: 15,
    fontWeight: '900',
  },
  clientStatLabel: {
    color: '#557669',
    fontSize: 11,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  clientStatPill: {
    backgroundColor: '#FFFFFF',
    borderColor: 'rgba(18, 56, 44, 0.1)',
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    gap: 4,
    minWidth: 116,
    padding: 10,
  },
  clientStatsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  clientStatsToggle: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: '#FFFFFF',
    borderColor: 'rgba(0, 141, 73, 0.24)',
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 7,
    minHeight: 42,
    paddingHorizontal: 12,
  },
  clientStatsToggleActive: {
    backgroundColor: '#008D49',
    borderColor: '#008D49',
  },
  clientStatsToggleText: {
    color: '#008D49',
    fontSize: 13,
    fontWeight: '900',
  },
  clientStatsToggleTextActive: {
    color: '#F4FAF6',
  },
  clientStatsToggleValue: {
    color: '#12382C',
    fontSize: 13,
    fontWeight: '900',
  },
  clientStatValue: {
    color: '#12382C',
    fontSize: 20,
    fontWeight: '900',
  },
  clientWelcomePanel: {
    gap: 7,
    paddingBottom: 2,
    paddingTop: 4,
  },
  clientWelcomeText: {
    color: kinetixColors.textSecondary,
    fontSize: kinetixTypography.sizes.body,
    fontWeight: kinetixTypography.weights.medium,
    lineHeight: kinetixTypography.lineHeights.body,
  },
  clientWelcomeTitle: {
    color: kinetixColors.textPrimary,
    fontSize: kinetixTypography.sizes.headline - 2,
    fontWeight: kinetixTypography.weights.bold,
    lineHeight: kinetixTypography.lineHeights.headline - 2,
  },
  contentPanel: {
    backgroundColor: '#FFFFFF',
    borderColor: 'rgba(18, 56, 44, 0.12)',
    borderRadius: 8,
    borderWidth: 1,
    gap: 10,
    padding: 12,
  },
  commandCopy: {
    flex: 1,
    gap: 5,
    minWidth: 0,
  },
  commandEyebrow: {
    color: '#008D49',
    fontSize: 11,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  commandFootnote: {
    color: '#006BB6',
    fontSize: 12,
    fontWeight: '900',
    lineHeight: 17,
  },
  commandHeader: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 12,
  },
  commandIconOnline: {
    backgroundColor: '#FFFFFF',
  },
  commandIconPrimary: {
    alignItems: 'center',
    backgroundColor: '#DDF1E7',
    borderRadius: 8,
    height: 54,
    justifyContent: 'center',
    width: 54,
  },
  commandMetaDivider: {
    alignSelf: 'stretch',
    backgroundColor: 'rgba(18, 56, 44, 0.14)',
    width: 1,
  },
  commandMetaItem: {
    flex: 1,
    gap: 4,
    minWidth: 0,
  },
  commandMetaLabel: {
    color: '#557669',
    fontSize: 11,
    fontWeight: '800',
    lineHeight: 15,
  },
  commandMetaStrip: {
    backgroundColor: '#F7FBF8',
    borderColor: 'rgba(0, 141, 73, 0.16)',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    padding: 10,
  },
  commandMetaValue: {
    color: '#12382C',
    fontSize: 18,
    fontWeight: '900',
    lineHeight: 22,
  },
  commandPanel: {
    backgroundColor: '#FFFFFF',
    borderColor: '#008D49',
    borderRadius: 8,
    borderWidth: 1,
    elevation: 2,
    gap: 12,
    padding: 14,
    shadowColor: 'rgba(18, 56, 44, 0.18)',
    shadowOffset: { height: 3, width: 0 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
  },
  commandPanelOnline: {
    backgroundColor: '#F3FBF6',
    borderColor: '#008D49',
  },
  commandPrimaryButton: {
    alignItems: 'center',
    backgroundColor: '#008D49',
    borderColor: '#008D49',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'center',
    elevation: 2,
    minHeight: 68,
    paddingHorizontal: 14,
    shadowColor: 'rgba(0, 111, 58, 0.24)',
    shadowOffset: { height: 3, width: 0 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
  },
  commandPrimaryButtonDisabled: {
    backgroundColor: '#A9BBB3',
    borderColor: '#A9BBB3',
  },
  commandPrimaryButtonOnline: {
    backgroundColor: '#FFFFFF',
    borderColor: '#008D49',
    shadowOpacity: 0.08,
  },
  commandPrimaryButtonText: {
    color: '#F4FAF6',
    fontSize: 18,
    fontWeight: '900',
  },
  commandPrimaryButtonTextOnline: {
    color: '#008D49',
  },
  commandSecondaryButton: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: 'rgba(0, 141, 73, 0.24)',
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    flexDirection: 'row',
    gap: 7,
    justifyContent: 'center',
    minHeight: 44,
    minWidth: 104,
    paddingHorizontal: 12,
  },
  commandSecondaryButtonActive: {
    backgroundColor: '#008D49',
    borderColor: '#008D49',
  },
  commandSecondaryButtonText: {
    color: '#008D49',
    fontSize: 13,
    fontWeight: '900',
  },
  commandSecondaryButtonTextActive: {
    color: '#F4FAF6',
  },
  commandSecondaryRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  commandSwitchCopy: {
    flex: 1,
    gap: 3,
    minWidth: 0,
  },
  commandSwitchRow: {
    alignItems: 'center',
    backgroundColor: '#E8F3EF',
    borderRadius: 8,
    flexDirection: 'row',
    gap: 12,
    minHeight: 64,
    padding: 10,
  },
  commandSwitchText: {
    color: '#557669',
    fontSize: 12,
    lineHeight: 17,
  },
  commandSwitchTitle: {
    color: '#12382C',
    fontSize: 14,
    fontWeight: '900',
  },
  commandText: {
    color: '#557669',
    fontSize: 13,
    lineHeight: 18,
  },
  commandTitle: {
    color: '#12382C',
    fontSize: 26,
    fontWeight: '900',
    lineHeight: 30,
  },
  driverLineButton: {
    alignItems: 'center',
    backgroundColor: '#008D49',
    borderColor: '#008D49',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 14,
    minHeight: 88,
    padding: 12,
  },
  driverLineButtonDisabled: {
    backgroundColor: '#A9BBB3',
    borderColor: '#A9BBB3',
  },
  driverLineButtonOnline: {
    backgroundColor: '#E8F3EF',
    borderColor: '#008D49',
  },
  driverLineCopy: {
    flex: 1,
    gap: 3,
    minWidth: 0,
  },
  driverLineHint: {
    color: '#E8F3EF',
    fontSize: 13,
    fontWeight: '800',
    lineHeight: 18,
  },
  driverLineIcon: {
    alignItems: 'center',
    backgroundColor: '#008D49',
    borderRadius: 8,
    height: 46,
    justifyContent: 'center',
    width: 46,
  },
  driverLineIconOnline: {
    backgroundColor: '#FFFFFF',
  },
  driverLineLabel: {
    color: '#E8F3EF',
    fontSize: 13,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  driverLineTextOnline: {
    color: '#008D49',
  },
  driverLineValue: {
    color: '#F4FAF6',
    fontSize: 24,
    fontWeight: '900',
    lineHeight: 28,
  },
  driverLineCar: {
    alignItems: 'center',
    backgroundColor: '#008D49',
    borderColor: '#FFFFFF',
    borderRadius: 8,
    borderWidth: 2,
    height: 42,
    justifyContent: 'center',
    position: 'absolute',
    right: 34,
    top: 31,
    width: 42,
  },
  driverLineFinishDot: {
    backgroundColor: '#12382C',
    borderColor: '#008D49',
    borderRadius: 999,
    borderWidth: 2,
    bottom: 24,
    height: 18,
    position: 'absolute',
    right: 26,
    width: 18,
  },
  driverLineMapLayer: {
    backgroundColor: '#DDF1E7',
    borderRadius: 8,
    height: 104,
    overflow: 'hidden',
    position: 'relative',
  },
  driverLineMiniLabel: {
    color: '#557669',
    fontSize: 10,
    fontWeight: '900',
  },
  driverLineMiniStat: {
    backgroundColor: '#FFFFFF',
    borderColor: 'rgba(0, 141, 73, 0.18)',
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    gap: 2,
    minWidth: 92,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  driverLineMiniStats: {
    flexDirection: 'row',
    gap: 8,
  },
  driverLineMiniValue: {
    color: '#12382C',
    fontSize: 17,
    fontWeight: '900',
  },
  driverLineRoad: {
    backgroundColor: 'rgba(255,255,255,0.7)',
    height: 18,
    left: -14,
    position: 'absolute',
    right: -14,
    top: 34,
  },
  driverLineRoadOne: {
    transform: [{ rotate: '-17deg' }],
  },
  driverLineRoadTwo: {
    top: 65,
    transform: [{ rotate: '22deg' }],
  },
  driverLineRoute: {
    backgroundColor: '#008D49',
    borderRadius: 99,
    height: 5,
    left: 28,
    position: 'absolute',
    right: 42,
    top: 53,
    transform: [{ rotate: '9deg' }],
  },
  driverLineStartDot: {
    backgroundColor: '#FFFFFF',
    borderColor: '#008D49',
    borderRadius: 999,
    borderWidth: 2,
    height: 18,
    left: 24,
    position: 'absolute',
    top: 48,
    width: 18,
  },
  driverLineVisual: {
    backgroundColor: '#F7FBF8',
    borderColor: 'rgba(0, 141, 73, 0.16)',
    borderRadius: 8,
    borderWidth: 1,
    gap: 10,
    padding: 10,
  },
  driverLineVisualCopy: {
    gap: 3,
  },
  driverLineVisualOnline: {
    backgroundColor: '#EEF8F1',
    borderColor: 'rgba(0, 141, 73, 0.32)',
  },
  driverLineVisualText: {
    color: '#557669',
    fontSize: 12,
    fontWeight: '800',
  },
  driverLineVisualTitle: {
    color: '#12382C',
    fontSize: 17,
    fontWeight: '900',
  },
  driverAccessCopy: {
    flex: 1,
    gap: 3,
    minWidth: 0,
  },
  driverAccessIcon: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    height: 34,
    justifyContent: 'center',
    width: 34,
  },
  driverAccessStrip: {
    alignItems: 'flex-start',
    backgroundColor: '#E8F3EF',
    borderRadius: 8,
    flexDirection: 'row',
    gap: 10,
    padding: 10,
  },
  driverAccessText: {
    color: '#557669',
    fontSize: 12,
    lineHeight: 17,
  },
  driverAccessTitle: {
    color: '#12382C',
    fontSize: 14,
    fontWeight: '900',
  },
  driverStatsCard: {
    backgroundColor: '#FFFFFF',
    borderColor: '#008D49',
    borderRadius: 8,
    borderWidth: 1,
    gap: 10,
    padding: 14,
  },
  driverStatsHint: {
    color: '#008D49',
    fontSize: 13,
    fontWeight: '900',
  },
  driverStatsRows: {
    gap: 8,
  },
  driverStatsTitle: {
    color: '#12382C',
    fontSize: 16,
    fontWeight: '900',
  },
  fleetInviteButton: {
    alignItems: 'center',
    backgroundColor: '#008D49',
    borderRadius: 8,
    justifyContent: 'center',
    minHeight: 46,
    paddingHorizontal: 12,
  },
  fleetInviteButtonText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '900',
    textAlign: 'center',
  },
  fleetInviteCodeBox: {
    backgroundColor: '#E8F3EF',
    borderRadius: 8,
    gap: 4,
    padding: 10,
  },
  fleetInviteCodeLabel: {
    color: '#557669',
    fontSize: 11,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  fleetInviteCodeValue: {
    color: '#12382C',
    fontSize: 18,
    fontWeight: '900',
  },
  fleetInviteCopy: {
    flex: 1,
    gap: 3,
    minWidth: 0,
  },
  fleetInviteHeader: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 10,
  },
  fleetInviteIcon: {
    alignItems: 'center',
    backgroundColor: '#E8F3EF',
    borderRadius: 8,
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  fleetInvitePanel: {
    backgroundColor: '#FFFFFF',
    borderColor: '#008D49',
    borderRadius: 8,
    borderWidth: 1,
    gap: 10,
    padding: 12,
  },
  fleetInviteText: {
    color: '#557669',
    fontSize: 12,
    lineHeight: 17,
  },
  fleetInviteTitle: {
    color: '#12382C',
    fontSize: 14,
    fontWeight: '900',
  },
  financePanel: {
    backgroundColor: '#FFFFFF',
    borderColor: '#008D49',
    borderRadius: 8,
    borderWidth: 1,
    gap: 12,
    padding: 12,
  },
  payoutActionsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  payoutHeroBadge: {
    backgroundColor: 'rgba(183, 244, 106, 0.22)',
    borderColor: 'rgba(0, 141, 73, 0.26)',
    borderRadius: 999,
    borderWidth: 1,
    color: '#006F3A',
    fontSize: 11,
    fontWeight: '900',
    overflow: 'hidden',
    paddingHorizontal: 8,
    paddingVertical: 5,
  },
  payoutHeroCard: {
    backgroundColor: '#FFFFFF',
    borderColor: 'rgba(0, 141, 73, 0.22)',
    borderRadius: 8,
    borderWidth: 1,
    elevation: 2,
    gap: 12,
    padding: 14,
    shadowColor: 'rgba(18, 56, 44, 0.18)',
    shadowOffset: { height: 3, width: 0 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
  },
  payoutHeroCopy: {
    flex: 1,
    gap: 2,
    minWidth: 0,
  },
  payoutHeroIcon: {
    alignItems: 'center',
    backgroundColor: '#008D49',
    borderRadius: 8,
    height: 50,
    justifyContent: 'center',
    width: 50,
  },
  payoutHeroText: {
    color: '#557669',
    fontSize: 13,
    fontWeight: '800',
  },
  payoutHeroTitle: {
    color: '#12382C',
    fontSize: 30,
    fontWeight: '900',
    lineHeight: 34,
  },
  payoutHeroTop: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
  },
  payoutKeyCard: {
    backgroundColor: '#F7FBF8',
    borderColor: 'rgba(0, 141, 73, 0.16)',
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    gap: 3,
    minWidth: 118,
    padding: 10,
  },
  payoutKeyGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  payoutKeyLabel: {
    color: '#557669',
    fontSize: 11,
    fontWeight: '900',
  },
  payoutKeyValue: {
    color: '#12382C',
    fontSize: 18,
    fontWeight: '900',
  },
  payoutPage: {
    gap: 12,
  },
  payoutPayButton: {
    alignItems: 'center',
    backgroundColor: '#008D49',
    borderColor: '#008D49',
    borderRadius: 8,
    borderWidth: 1,
    elevation: 2,
    flex: 1,
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'center',
    minHeight: 50,
    minWidth: 190,
    paddingHorizontal: 14,
    shadowColor: 'rgba(0, 111, 58, 0.22)',
    shadowOffset: { height: 3, width: 0 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
  },
  payoutPayButtonText: {
    color: '#F4FAF6',
    fontSize: 14,
    fontWeight: '900',
  },
  payoutStatsButton: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: 'rgba(0, 141, 73, 0.24)',
    borderRadius: 8,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 50,
    minWidth: 118,
    paddingHorizontal: 12,
  },
  payoutStatsButtonActive: {
    backgroundColor: '#008D49',
    borderColor: '#008D49',
  },
  payoutStatsButtonText: {
    color: '#008D49',
    fontSize: 13,
    fontWeight: '900',
  },
  payoutStatsButtonTextActive: {
    color: '#F4FAF6',
  },
  payoutTariffChip: {
    backgroundColor: '#FFFFFF',
    borderColor: 'rgba(0, 141, 73, 0.2)',
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    gap: 3,
    minHeight: 58,
    minWidth: 130,
    padding: 12,
  },
  payoutTariffChipActive: {
    backgroundColor: '#008D49',
    borderColor: '#008D49',
  },
  payoutTariffRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  payoutTariffText: {
    color: '#008D49',
    fontSize: 16,
    fontWeight: '900',
  },
  payoutTariffTextActive: {
    color: '#F4FAF6',
  },
  payoutTariffTitle: {
    color: '#557669',
    fontSize: 12,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  payoutTariffTitleActive: {
    color: '#DDF1E7',
  },
  driverFeedAcceptButton: {
    alignItems: 'center',
    backgroundColor: '#008D49',
    borderRadius: 8,
    justifyContent: 'center',
    minHeight: 38,
    paddingHorizontal: 10,
  },
  disabledButton: {
    backgroundColor: '#A9BBB3',
    borderColor: '#A9BBB3',
  },
  driverFeedAcceptText: {
    color: '#F4FAF6',
    fontSize: 14,
    fontWeight: '900',
  },
  driverFeedAcceptProgress: {
    backgroundColor: '#B7F46A',
    borderRadius: 999,
    height: 3,
    width: '42%',
  },
  driverFeedActions: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    marginTop: 2,
  },
  driverFeedAcceptButtonWide: {
    flex: 1,
    minHeight: 44,
  },
  driverFeedAddress: {
    color: '#12382C',
    flex: 1,
    fontSize: 15,
    fontWeight: '900',
    minWidth: 0,
  },
  driverFeedCardTags: {
    alignItems: 'center',
    flexDirection: 'row',
    flexShrink: 1,
    gap: 8,
    minWidth: 0,
  },
  driverFeedCardTop: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'space-between',
  },
  driverFeedRouteRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  driverFeedBadge: {
    backgroundColor: '#FFFFFF',
    borderColor: 'rgba(0, 141, 73, 0.18)',
    borderRadius: 6,
    borderWidth: 1,
    color: '#008D49',
    fontSize: 10,
    fontWeight: '900',
    overflow: 'hidden',
    paddingHorizontal: 6,
    paddingVertical: 3,
  },
  driverFeedBadges: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 5,
  },
  driverFeedCard: {
    backgroundColor: '#FFFFFF',
    borderColor: 'rgba(0, 141, 73, 0.16)',
    borderRadius: 8,
    borderWidth: 1,
    elevation: 1,
    gap: 8,
    padding: 10,
    shadowColor: 'rgba(18, 56, 44, 0.16)',
    shadowOffset: { height: 5, width: 0 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
  },
  driverFeedCardRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 7,
  },
  driverFeedCount: {
    backgroundColor: '#F1F8F3',
    borderRadius: 8,
    color: '#008D49',
    fontSize: 16,
    fontWeight: '900',
    minWidth: 38,
    overflow: 'hidden',
    paddingHorizontal: 10,
    paddingVertical: 7,
    textAlign: 'center',
  },
  driverFeedDetails: {
    backgroundColor: '#F7FBF8',
    borderRadius: 8,
    gap: 6,
    padding: 8,
  },
  driverFeedDistance: {
    color: '#006F3A',
    fontSize: 13,
    fontWeight: '800',
  },
  driverFeedService: {
    backgroundColor: '#EAF6EF',
    borderColor: 'rgba(0, 141, 73, 0.18)',
    borderRadius: 6,
    borderWidth: 1,
    color: '#008D49',
    fontSize: 10,
    fontWeight: '900',
    maxWidth: 72,
    overflow: 'hidden',
    paddingHorizontal: 6,
    paddingVertical: 4,
    textAlign: 'center',
  },
  driverFeedEmpty: {
    backgroundColor: '#FFFFFF',
    borderColor: 'rgba(18, 56, 44, 0.1)',
    borderRadius: 8,
    borderWidth: 1,
    gap: 4,
    padding: 12,
  },
  driverFeedEmptyText: {
    color: '#557669',
    fontSize: 12,
    lineHeight: 17,
  },
  driverFeedEmptyTitle: {
    color: '#12382C',
    fontSize: 14,
    fontWeight: '900',
  },
  driverFeedFullButton: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: 'rgba(0, 141, 73, 0.28)',
    borderRadius: 8,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 42,
    paddingHorizontal: 12,
  },
  driverFeedFullButtonText: {
    color: '#12382C',
    fontSize: 13,
    fontWeight: '900',
  },
  driverFeedHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'space-between',
  },
  driverFeedInfoButton: {
    alignItems: 'center',
    backgroundColor: '#F1F8F3',
    borderColor: 'rgba(0, 141, 73, 0.32)',
    borderRadius: 8,
    borderWidth: 1,
    height: 38,
    justifyContent: 'center',
    width: 38,
  },
  driverFeedInfoButtonActive: {
    backgroundColor: '#008D49',
  },
  driverFeedInfoText: {
    color: '#008D49',
    fontSize: 16,
    fontWeight: '900',
  },
  driverFeedInfoTextActive: {
    color: '#F4FAF6',
  },
  driverFeedList: {
    gap: 8,
  },
  driverFeedMeta: {
    color: '#557669',
    fontSize: 12,
    fontWeight: '800',
  },
  driverFeedNotice: {
    backgroundColor: '#FFF7E8',
    borderColor: '#E2A93B',
    borderRadius: 8,
    borderWidth: 1,
    padding: 10,
  },
  driverFeedNoticeText: {
    color: '#7A5520',
    fontSize: 12,
    fontWeight: '900',
    lineHeight: 17,
  },
  driverFeedPanel: {
    backgroundColor: '#FFFFFF',
    borderColor: 'rgba(0, 141, 73, 0.2)',
    borderRadius: 8,
    borderWidth: 1,
    elevation: 2,
    gap: 10,
    padding: 12,
    shadowColor: 'rgba(18, 56, 44, 0.18)',
    shadowOffset: { height: 6, width: 0 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
  },
  driverFeedPrice: {
    color: '#008D49',
    fontSize: 16,
    fontWeight: '900',
    minWidth: 66,
    textAlign: 'right',
  },
  driverFeedRouteDot: {
    backgroundColor: '#008D49',
    borderRadius: 999,
    height: 8,
    width: 8,
  },
  driverFeedRouteLine: {
    backgroundColor: 'rgba(0, 141, 73, 0.28)',
    borderRadius: 999,
    height: 18,
    width: 2,
  },
  driverFeedRouteMark: {
    alignItems: 'center',
    width: 12,
  },
  driverFeedSubtitle: {
    color: '#557669',
    fontSize: 12,
    fontWeight: '800',
  },
  driverFeedSignal: {
    backgroundColor: '#F1F8F3',
    borderColor: 'rgba(0, 141, 73, 0.18)',
    borderRadius: 999,
    borderWidth: 1,
    color: '#006F3A',
    fontSize: 11,
    fontWeight: '900',
    overflow: 'hidden',
    paddingHorizontal: 8,
    paddingVertical: 5,
  },
  driverFeedSignalRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  driverFeedTitle: {
    color: '#12382C',
    fontSize: 18,
    fontWeight: '900',
  },
  heroCopy: {
    flex: 1,
    gap: 6,
    minWidth: 0,
  },
  heroIcon: {
    alignItems: 'center',
    backgroundColor: '#E8F3EF',
    borderRadius: 8,
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  heroPanel: {
    alignItems: 'flex-start',
    backgroundColor: '#FFFFFF',
    borderColor: '#008D49',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    padding: 12,
  },
  heroText: {
    color: '#557669',
    fontSize: 13,
    lineHeight: 18,
  },
  heroTitle: {
    color: '#12382C',
    fontSize: 20,
    fontWeight: '900',
    lineHeight: 24,
  },
  hello: {
    color: '#12382C',
    fontSize: 16,
    fontWeight: '900',
  },
  layout: {
    gap: 12,
  },
  liveDot: {
    backgroundColor: '#5C8D89',
    borderRadius: 5,
    height: 10,
    marginTop: 4,
    width: 10,
  },
  liveDotActive: {
    backgroundColor: '#7A9A7E',
  },
  livePanel: {
    alignItems: 'flex-start',
    backgroundColor: '#FFFFFF',
    borderColor: '#008D49',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 9,
    padding: 12,
  },
  livePanelText: {
    color: '#12382C',
    flex: 1,
    fontSize: 13,
    fontWeight: '800',
    lineHeight: 18,
  },
  layoutWide: {
    alignItems: 'flex-start',
    flexDirection: 'row',
  },
  main: {
    flex: 1,
    gap: 10,
    minWidth: 0,
  },
  menuToggle: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#008D49',
    borderRadius: 8,
    borderWidth: 1,
    height: 46,
    justifyContent: 'center',
    width: 46,
  },
  menuButton: {
    alignItems: 'flex-start',
    backgroundColor: '#FFFFFF',
    borderColor: '#008D49',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 9,
    padding: 10,
  },
  menuButtonCompact: {
    alignItems: 'center',
    minHeight: 76,
    width: 152,
  },
  menuButtonActive: {
    backgroundColor: '#E8F3EF',
    borderColor: '#008D49',
  },
  menuCopy: {
    flex: 1,
    gap: 4,
    minWidth: 0,
  },
  menuIconWrap: {
    alignItems: 'center',
    backgroundColor: '#E8F3EF',
    borderRadius: 8,
    height: 32,
    justifyContent: 'center',
    width: 32,
  },
  menuIconWrapCompact: {
    height: 34,
    width: 34,
  },
  menuIconWrapActive: {
    backgroundColor: '#008D49',
  },
  menuList: {
    gap: 8,
  },
  menuRail: {
    gap: 8,
    paddingRight: 4,
  },
  menuSubtitle: {
    color: '#557669',
    fontSize: 12,
    lineHeight: 17,
  },
  menuTitle: {
    color: '#12382C',
    flexShrink: 1,
    fontSize: 14,
    fontWeight: '900',
  },
  menuTitleActive: {
    color: '#008D49',
  },
  menuTitleRow: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  metricCard: {
    flex: 1,
    gap: 2,
    minWidth: 92,
  },
  metricLabel: {
    color: '#71877D',
    fontSize: 12,
    fontWeight: '600',
    lineHeight: 16,
  },
  metricsGrid: {
    columnGap: 18,
    flexDirection: 'row',
    flexWrap: 'wrap',
    paddingVertical: 4,
    rowGap: 14,
  },
  metricValue: {
    color: '#12382C',
    fontSize: 20,
    fontWeight: '900',
  },
  miniStat: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 10,
    paddingVertical: 8,
  },
  miniStatLabel: {
    color: '#557669',
    fontSize: 13,
    fontWeight: '600',
  },
  miniStatValue: {
    color: '#12382C',
    fontSize: 14,
    fontWeight: '900',
    textAlign: 'right',
  },
  notePanel: {
    alignItems: 'flex-start',
    backgroundColor: '#FFFFFF',
    borderColor: '#008D49',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    padding: 14,
  },
  noteText: {
    color: '#12382C',
    flex: 1,
    fontSize: 13,
    lineHeight: 19,
  },
  outlineButton: {
    alignItems: 'center',
    borderColor: '#008D49',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 7,
    minHeight: 42,
    justifyContent: 'center',
    paddingHorizontal: 14,
  },
  outlineButtonText: {
    color: '#008D49',
    fontSize: 14,
    fontWeight: '900',
  },
  orderButton: {
    alignItems: 'center',
    backgroundColor: '#008D49',
    borderRadius: 8,
    flexDirection: 'row',
    gap: 8,
    minHeight: 42,
    justifyContent: 'center',
    paddingHorizontal: 14,
  },
  orderButtonText: {
    color: '#F4FAF6',
    fontSize: 14,
    fontWeight: '900',
  },
  page: {
    backgroundColor: '#F6F8F5',
    gap: 14,
    minHeight: '100%',
    padding: 14,
    paddingBottom: 20,
  },
  panelSubtitle: {
    color: '#557669',
    fontSize: 14,
    lineHeight: 20,
  },
  panelTitle: {
    color: '#12382C',
    fontSize: 18,
    fontWeight: '900',
  },
  pressed: {
    opacity: 0.92,
    transform: [{ scale: 0.95 }],
  },
  primaryButton: {
    alignItems: 'center',
    backgroundColor: '#008D49',
    borderRadius: 8,
    elevation: 2,
    justifyContent: 'center',
    minHeight: 46,
    paddingHorizontal: 14,
    shadowColor: 'rgba(0, 111, 58, 0.22)',
    shadowOffset: { height: 7, width: 0 },
    shadowOpacity: 0.14,
    shadowRadius: 14,
  },
  primaryButtonText: {
    color: '#F4FAF6',
    fontSize: 14,
    fontWeight: '900',
  },
  profileCopy: {
    flex: 1,
    gap: 3,
    minWidth: 0,
  },
  profilePanel: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#008D49',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    padding: 12,
  },
  profileStatus: {
    color: '#557669',
    fontSize: 13,
    lineHeight: 18,
  },
  quickCard: {
    backgroundColor: '#E8F3EF',
    borderColor: '#008D49',
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    gap: 8,
    minHeight: 104,
    minWidth: 150,
    padding: 12,
  },
  quickGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  quickGridItem: {
    flex: 1,
    flexDirection: 'row',
    minWidth: 150,
  },
  quickIconWrap: {
    alignItems: 'center',
    backgroundColor: '#E8F3EF',
    borderRadius: 8,
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  quickSubtitle: {
    color: '#557669',
    fontSize: 12,
    lineHeight: 17,
  },
  quickTitle: {
    color: '#12382C',
    fontSize: 15,
    fontWeight: '900',
  },
  routeDivider: {
    color: '#557669',
    fontSize: 13,
    fontWeight: '800',
  },
  routeRow: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 7,
  },
  routeText: {
    color: '#557669',
    fontSize: 13,
    fontWeight: '800',
  },
  routeTextActive: {
    color: '#008D49',
    fontSize: 13,
    fontWeight: '900',
  },
  routePreview: {
    alignItems: 'flex-start',
    backgroundColor: '#E8F3EF',
    borderRadius: 8,
    flexDirection: 'row',
    gap: 10,
    padding: 10,
  },
  routePreviewCopy: {
    flex: 1,
    gap: 3,
    minWidth: 0,
  },
  routePreviewDot: {
    backgroundColor: '#008D49',
    borderColor: '#FFFFFF',
    borderRadius: 7,
    borderWidth: 2,
    height: 14,
    width: 14,
  },
  routePreviewDotEnd: {
    backgroundColor: '#006BB6',
  },
  routePreviewLine: {
    backgroundColor: '#008D49',
    flex: 1,
    width: 2,
  },
  routePreviewRail: {
    alignItems: 'center',
    height: 48,
    paddingVertical: 2,
    width: 18,
  },
  routePreviewText: {
    color: '#557669',
    fontSize: 12,
    lineHeight: 17,
  },
  routePreviewTitle: {
    color: '#12382C',
    fontSize: 14,
    fontWeight: '900',
  },
  secondaryButton: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#008D49',
    borderRadius: 8,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 46,
    paddingHorizontal: 14,
  },
  secondaryButtonText: {
    color: '#12382C',
    fontSize: 14,
    fontWeight: '900',
  },
  sectionRow: {
    alignItems: 'flex-start',
    backgroundColor: '#E8F3EF',
    borderColor: '#008D49',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    justifyContent: 'space-between',
    padding: 10,
  },
  sectionRowCopy: {
    flex: 1,
    gap: 4,
    minWidth: 150,
  },
  sectionRowMeta: {
    alignItems: 'flex-end',
    gap: 4,
    minWidth: 92,
  },
  sectionRows: {
    gap: 9,
  },
  sectionRowStatus: {
    backgroundColor: '#E8F3EF',
    borderRadius: 6,
    color: '#008D49',
    fontSize: 11,
    fontWeight: '900',
    overflow: 'hidden',
    paddingHorizontal: 7,
    paddingVertical: 4,
  },
  sectionRowSubtitle: {
    color: '#557669',
    fontSize: 12,
    lineHeight: 17,
  },
  sectionRowTitle: {
    color: '#12382C',
    fontSize: 14,
    fontWeight: '900',
  },
  sectionRowValue: {
    color: '#12382C',
    fontSize: 14,
    fontWeight: '900',
    textAlign: 'right',
  },
  simpleModeButton: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#008D49',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    minHeight: 74,
    padding: 12,
  },
  simpleModeCopy: {
    flex: 1,
    gap: 3,
    minWidth: 0,
  },
  simpleModeKnob: {
    backgroundColor: '#557669',
    borderRadius: 10,
    height: 20,
    width: 20,
  },
  simpleModeKnobActive: {
    alignSelf: 'flex-end',
    backgroundColor: '#F4FAF6',
  },
  simpleModeSwitch: {
    backgroundColor: '#E8F3EF',
    borderColor: '#557669',
    borderRadius: 99,
    borderWidth: 1,
    justifyContent: 'center',
    padding: 3,
    width: 50,
  },
  simpleModeSwitchActive: {
    backgroundColor: '#008D49',
    borderColor: '#008D49',
  },
  simpleModeText: {
    color: '#557669',
    fontSize: 12,
    lineHeight: 17,
  },
  simpleModeTitle: {
    color: '#12382C',
    fontSize: 14,
    fontWeight: '900',
  },
  sidebar: {
    gap: 10,
    width: '100%',
  },
  sidebarWide: {
    flexShrink: 0,
    width: 340,
  },
  bottomTabs: {
    alignItems: 'stretch',
    backgroundColor: '#FFFFFF',
    borderColor: 'rgba(18, 56, 44, 0.12)',
    borderRadius: 8,
    borderWidth: 1,
    elevation: 2,
    flexDirection: 'row',
    gap: 6,
    justifyContent: 'space-between',
    marginBottom: 10,
    marginHorizontal: 10,
    paddingHorizontal: 10,
    paddingBottom: 10,
    paddingTop: 8,
    shadowColor: 'rgba(18, 56, 44, 0.18)',
    shadowOffset: { height: -6, width: 0 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
  },
  clientBottomTabs: {
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: kinetixColors.surface,
    borderColor: kinetixColors.line,
    borderRadius: kinetixRadii.mapPin,
    borderWidth: kinetixBorders.hairline,
    elevation: 14,
    gap: kinetixSpacing.xs,
    justifyContent: 'center',
    marginBottom: kinetixSpacing.md,
    marginHorizontal: kinetixSpacing.xl,
    paddingBottom: kinetixSpacing.xs,
    paddingHorizontal: kinetixSpacing.xs,
    paddingTop: kinetixSpacing.xs,
    shadowColor: kinetixColors.shadow,
    shadowOffset: { height: 10, width: 0 },
    shadowOpacity: 0.16,
    shadowRadius: 22,
  },
  bottomTab: {
    alignItems: 'center',
    borderRadius: 8,
    flex: 1,
    gap: 4,
    justifyContent: 'center',
    minHeight: 58,
    minWidth: 0,
    paddingHorizontal: 4,
    position: 'relative',
  },
  clientBottomTab: {
    borderRadius: kinetixRadii.mapPin,
    flex: 0,
    minHeight: kinetixTouchTargets.icon,
    minWidth: 74,
    paddingHorizontal: kinetixSpacing.xs,
  },
  bottomTabActive: {
    backgroundColor: '#F1F8F3',
  },
  clientBottomTabActive: {
    backgroundColor: 'transparent',
  },
  bottomTabIndicator: {
    backgroundColor: 'transparent',
    borderRadius: 999,
    height: 3,
    position: 'absolute',
    top: 5,
    width: 22,
  },
  bottomTabIndicatorActive: {
    backgroundColor: kinetixColors.amber,
  },
  bottomTabIcon: {
    alignItems: 'center',
    borderRadius: 8,
    height: 30,
    justifyContent: 'center',
    width: 30,
  },
  clientBottomTabIcon: {
    borderRadius: kinetixRadii.mapPin,
    height: 28,
    width: 28,
  },
  bottomTabIconActive: {
    backgroundColor: kinetixColors.amber,
  },
  bottomTabText: {
    color: kinetixColors.textSecondary,
    fontSize: 11,
    fontWeight: '800',
    textAlign: 'center',
  },
  bottomTabTextActive: {
    color: kinetixColors.amber,
  },
  drawerRoot: {
    flex: 1,
    flexDirection: 'row',
  },
  drawerScrim: {
    backgroundColor: 'rgba(18, 56, 44, 0.34)',
    flex: 1,
  },
  drawerPanel: {
    backgroundColor: '#F6F8F5',
    borderRightColor: 'rgba(18, 56, 44, 0.12)',
    borderRightWidth: 1,
    elevation: 12,
    gap: 12,
    maxWidth: 360,
    padding: 14,
    shadowColor: 'rgba(18, 56, 44, 0.22)',
    shadowOffset: { height: 0, width: 10 },
    shadowOpacity: 0.16,
    shadowRadius: 24,
    width: '86%',
  },
  drawerHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'space-between',
  },
  drawerTitleCopy: {
    flex: 1,
    minWidth: 0,
  },
  drawerTitle: {
    color: '#12382C',
    fontSize: 19,
    fontWeight: '900',
  },
  drawerSubtitle: {
    color: '#557669',
    fontSize: 13,
    marginTop: 2,
  },
  drawerClose: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: 'rgba(18, 56, 44, 0.12)',
    borderRadius: 8,
    borderWidth: 1,
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  drawerList: {
    gap: 8,
    paddingBottom: 18,
  },
  drawerItem: {
    alignItems: 'flex-start',
    backgroundColor: '#FFFFFF',
    borderColor: 'rgba(18, 56, 44, 0.1)',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    minHeight: 58,
    padding: 10,
  },
  drawerItemActive: {
    backgroundColor: '#F1F8F3',
    borderColor: '#008D49',
  },
  drawerIconWrap: {
    alignItems: 'center',
    backgroundColor: '#E8F3EF',
    borderRadius: 8,
    height: 34,
    justifyContent: 'center',
    width: 34,
  },
  drawerIconWrapActive: {
    backgroundColor: '#008D49',
  },
  drawerItemCopy: {
    flex: 1,
    gap: 3,
    minWidth: 0,
  },
  drawerItemTitle: {
    color: '#12382C',
    fontSize: 14,
    fontWeight: '900',
  },
  drawerItemTitleActive: {
    color: '#008D49',
  },
  drawerItemSubtitle: {
    color: '#557669',
    fontSize: 12,
    lineHeight: 17,
  },
  statusPanel: {
    backgroundColor: '#E8F3EF',
    borderColor: '#008D49',
    borderRadius: 8,
    borderWidth: 1,
    gap: 10,
    padding: 12,
  },
  statusText: {
    color: '#557669',
    fontSize: 14,
    lineHeight: 20,
  },
  statusTitle: {
    color: '#008D49',
    fontSize: 18,
    fontWeight: '900',
  },
  topBar: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: 'rgba(18, 56, 44, 0.12)',
    borderRadius: 8,
    borderWidth: 1,
    elevation: 1,
    flexDirection: 'row',
    gap: 10,
    padding: 12,
    shadowColor: 'rgba(18, 56, 44, 0.14)',
    shadowOffset: { height: 3, width: 0 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
  },
  topActions: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
});
