// This file is generated by scripts/import-salavat-addresses.mjs.
// Do not edit manually: rerun the import script after refreshing OSM/GAR source data.

export type SalavatHouseSource = 'gar' | 'osm' | 'manual' | 'merged';

export type SalavatHouseRecord = {
  settlement: string;
  street: string;
  house: string;
  fullAddress: string;
  source: SalavatHouseSource;
  aliases: string[];
  coordinates?: {
    latitude: number;
    longitude: number;
  };
};

export const salavatDistrictHouseSourceSummary = {
  district: 'Салаватский район, Республика Башкортостан',
  osmRelationId: 398510,
  generatedAt: null,
  note:
    'Файл подготовлен для точного слоя домов. Запустите npm run import:salavat-addresses, чтобы собрать дома из открытых адресных тегов OpenStreetMap. Для продакшена дополнительно подключите официальный ГАР/ФИАС на сервере.',
  osmHouses: 0,
  garHouses: 0,
  manualHouses: 0,
  houses: 0,
} as const;

export const salavatDistrictHouses: SalavatHouseRecord[] = [];
