// This file is generated by scripts/import-salavat-addresses.mjs.
// Do not edit manually: rerun the import script after refreshing OSM/GAR source data.
//
// Лёгкие метаданные справочника домов вынесены отдельно от тяжёлого массива
// salavatDistrictHouses, чтобы статистику и типы можно было импортировать без
// затягивания ~8.7 МБ данных в стартовый бандл.

export type SalavatHouseSource = 'gar' | 'osm' | 'manual' | 'merged';

export type SalavatHouseRecord = {
  settlement: string;
  street: string;
  house: string;
  fullAddress: string;
  source: SalavatHouseSource;
  aliases: string[];
  coordinates?: {
    latitude: number;
    longitude: number;
  };
};

export const salavatDistrictHouseSourceSummary = {
  district: 'Салаватский район, Республика Башкортостан',
  fiasSourceUrl: 'https://fias.nalog-udc.ru/Home/Index/41940',
  fiasVersion: '26.05.2026',
  osmRelationId: 398510,
  generatedAt: '2026-05-26T17:20:38.268Z',
  note:
    'Дома собраны из онлайн-справочника ФИАС/ГАР ФНС по Салаватскому району и дополнены координатами из открытых адресных тегов OpenStreetMap. OSM импорт берет bbox вокруг района и фильтрует точки по relation 398510, чтобы не захватывать соседние города. Для продакшена импорт нужно перенести на сервер и регулярно сверять с официальной ГАР/ФИАС выгрузкой ФНС.',
  osmQueryMode: 'none',
  osmRawHouses: 0,
  osmHouses: 0,
  garHouses: 12561,
  manualHouses: 0,
  mergedHouses: 1068,
  osmOnlyHouses: 1796,
  garOnlyHouses: 11472,
  settlements: 71,
  streets: 454,
  poi: 0,
  houses: 14336,
} as const;
